### ISSUE TITLE
Leave multiple groups feature not visible

### ISSUE THREAD

**Issue by poopfarts1** [jshackles/Enhanced_Steam#1002]
Version 8.3 says that it added a way to leave multiple groups at once without having to reload the page. I am running version 8.4 and my groups page (http://steamcommunity.com/profiles/profile_id/groups) looks exactly the same whether I enable or disable the extension. I looked through the options to see if there was anything I have to change to enable this feature, but I didn't see anything. Am I doing something wrong? Thanks!

**Comment by JoiNNN** [comment]
Are you using Chrome? If you do and the problem persists try and reinstall the extension. If it works you should see those 2 buttons on the right and checkboxes
![chrome_2016-04-21_14-21-09](https://cloud.githubusercontent.com/assets/3322834/14708675/a19bdf54-07cc-11e6-99c4-3bdb4302c738.png)

**Comment by poopfarts1** [comment]
Hey there. I am using Chrome and I tried reinstalling but it did not fix it. I had a suspicion that it might have something to do with the custom url for the user profiles, so I tried something to test it. My main steam account has never set a custom url in the profile settings, so its group page url is in the form http://steamcommunity.com/profiles/steamID64/groups/ and my second account has a custom url, so its group page url is in the form http://steamcommunity.com/id/CustomURL/groups/. The checkboxes and leave buttons show up as they should for my second account, but not for my first. Perhaps the extension does not add those group features to non-custom url profiles? Maybe I just need to add a custom url for my main account haha. Thanks for your help!

**Comment by JoiNNN** [comment]
Hmmm, it might be that but it should also work for profiles, I wouldn't have noticed if it didn't since I have an id set. I'm looking into it.

**Comment by poopfarts1** [comment]
Just tried it and it output true.

**Comment by JoiNNN** [comment]
Indeed there seems to be a problem with the function which checks if a user is signed in, which doesn't account for profile urls.
Can you please confirm it? Go to http://store.steampowered.com/ make sure you are logged in and enter this in console `$J("#global_actions").find(".playerAvatar")[0].outerHTML.match(/\/id\/(.+?)"/);` it should output `null` if login check fails. Thanks.

**Comment by poopfarts1** [comment]
Yep, it output null.

**Comment by JoiNNN** [comment]
Fixed.
