### ISSUE TITLE
(Request) Have the last 1000 reviews of a game have its own rating

### ISSUE THREAD

**Issue by BarterClub** [jshackles/Enhanced_Steam#1014]
So i saw this on PCMR on reddit and was very curious if this could even happen. I hope this could happen. Its nice to know if a game changed from a bug or mircotations like (PayDay2). The link to the post and an image is below.

https://www.reddit.com/r/pcmasterrace/comments/4h4n04/something_that_could_be_useful/

**Comment by JoiNNN** [comment]
That's a nice idea, however, there are already extensions that do that (see FairSteam) and for something like this we would need a server side implementation on ES API. That's the hardest part, and whether is worth or not the coding for this feature is up to Jason.

**Comment by BarterClub** [comment]
Thanks

**Comment by jshackles** [comment]
Well it seems like Valve beat us to the punch this time!  The review system has been updated on Steam to show recent reviews.
