### ISSUE TITLE
the profile wont edit

### ISSUE THREAD

**Issue by nepnepnepnep** [jshackles/Enhanced_Steam#1015]
i have everything on default and my account's background or color wont change at all as this is the main reason i downloaded this  i would really love to know how to fix this

**Comment by jshackles** [comment]
Can you describe the steps you took or any error messages you may have encountered while attempting to edit your profile to make these changes?  "Won't change at all" is not descriptive enough for me to help you with this, unfortunately.

**Comment by nepnepnepnep** [comment]
i went on to edit profile on my page whilst signed in i scrolled down and went onto the change theme section i set the theme i then clicked the save option first after i did that when it wasnt working i waited about 20 minuets and then refreshed the page about 3 times i then tried clicking the save changes button and still nothing is that descriptive enough?

**Comment by jshackles** [comment]
When you hit "save" under the "Custom Background" section (this is correct, as "Save Changes at the bottom is the official button that will disregard any ES settings) were you redirected to the "Sign in through Steam" page?

**Comment by nepnepnepnep** [comment]
yes i was i clicked sign in and then was brought back to my profile exactly the same as it was before

**Comment by nepnepnepnep** [comment]
sorry it has now appeared on my profile it has sorted itself out
thx for trying to help anyway

**Comment by nepnepnepnep** [comment]
it is now working online and not on the downloaded version of steam is there anyway to fix that or does it only affect the online version

**Comment by jshackles** [comment]
Due to the nature of Enhanced Steam being a browser extension, it will only ever effect/change things which are loaded from your browser.  In this case, your profile customization selections are saved so that anyone else visiting your profile in a browser using Enhanced Steam will also see these changes.

Glad you were able to get it working!
