### ISSUE TITLE
[BUG] ES re-add removed tag for filter in greenlight list

### ISSUE THREAD

**Issue by VladimirMangos** [jshackles/Enhanced_Steam#1021]
I add Ganre:Simulation tag for filtering games in greenlight and now ES block my attempts remove tag.
At tag remove click page reloaded and tag re-added. If I disable ES then tag removed fine. BUT at ES enable tag readded back!

**Comment by seeeeew** [comment]
I can't reproduce what you're describing, but it might be related to the _Remember Greenlight filter options_ feature. You could try disabling that feature (under _Community_ → _Greenlight_).

**Comment by VladimirMangos** [comment]
You are right! After disable option filter start work expected for me. Early I think option remember state for next time page open and not prevent change filter explicitly.
