### ISSUE TITLE
Lowest price not showing when viewing item's I've listed on market (a picture of a cloud shows)

### ISSUE THREAD

**Issue by Grofff** [jshackles/Enhanced_Steam#1023]
As the title says, when I go to Steam -> Community -> Market (using Chrome) to view all the items I've listed it used to also show the lowest price of the items on the market. Now it's a white cloud and the lowest price will appear only if I left click the cloud.

How it looks:

http://i.imgur.com/Curq4Lt.jpg 

After I left click the price shows up:

http://i.imgur.com/iZS0DvF.jpg 

I've tried cleaning Enhanched Steams cache but it didn't help.

**Comment by seeeeew** [comment]
This was intentionally added in v8.1 to circumvent new Steam API limits.

Commit message (c7a84608e21e9eb819cc80091647a2b3fb99eefd):
> Since the API is limited now, if a user has more than 10 items in their
active selling list they will need to click on the "cloud" icon for each
item individually to check the lowest price.  :(

**Comment by jshackles** [comment]
Yes as @seeeeew said, Valve implemented an API limitation so unfortunately this is the result.  Prior to this workaround, when it tried to load everything at once, it would load a few items then start failing on the rest, with no way of knowing which items would load and which would fail.

This way, you can still check on the stuff you're interested in (or everything) as long as you don't exceed their limit of 10 items every 10 seconds.
