### ISSUE TITLE
Hide "New Releases - Popular New Releases"?

### ISSUE THREAD

**Issue by Blackbird88** [jshackles/Enhanced_Steam#1033]
Either I'm blind or dumb, but I don't see a way to hide this.
![image](https://cloud.githubusercontent.com/assets/4414625/15247320/c0b4a1ca-1913-11e6-8c17-c8e454f48ad5.png)

**Comment by seeeeew** [comment]
Uncheck *New Releases* in the *Customize* menu above the spotlight section (where the weekend deal is).

**Comment by Blackbird88** [comment]
I don't see it
![image](https://cloud.githubusercontent.com/assets/4414625/15250463/2ba2a782-1925-11e6-8b9a-97b6f8cff656.png)

**Comment by jshackles** [comment]
Valve changed the name of this section from .new_releases to .popular_new_releases.

As such, Enhanced Steam was updated yesterday to reflect this change, and the fix will be available when 8.5 releases (soon).

**Comment by Blackbird88** [comment]
Glad to hear that :)
