### ISSUE TITLE
[Bug] enhancedsteam.js:4298 Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by VladimirMangos** [jshackles/Enhanced_Steam#1048]
Found record in JS console at http://steamcommunity.com/market/ : 

enhancedsteam.js:4298 Uncaught TypeError: Cannot read property 'value' of null

Possible related (Sold!) entry in "My sell listings" part

**Comment by JoiNNN** [comment]
This is old, please open another issue if this still happens.
