### ISSUE TITLE
GTA SA DRM

### ISSUE THREAD

**Issue by Blackbird88** [jshackles/Enhanced_Steam#1059]
The game never had SecuROM in the first place. Only the retail version did.
http://steamcommunity.com/app/12120/discussions/0/34096318984412375/?ctp=24#c613941122653228443
Silent the creator of SilentPatch (unofficial patch for III/VC/SA) confirms it.

So please remove the
**Warning: This title uses 3rd party DRM (SecuROM)**

**Comment by jshackles** [comment]
It is the responsibility of the publisher to update their Steam page to state as such.  It currently reads:

> Other Requirements; Software installations required including DirectX and Sony DADC SecuROM. 

This sentence is listed in both the system requirements section as well as the legal notices section.  If Rockstar updates the store page and removes these items, the notice that Enhanced Steam provides to the users will go away as well.

**Comment by Blackbird88** [comment]
They will never do that lol and you know it.
