### ISSUE TITLE
Suggestion: inGameAppID

### ISSUE THREAD

**Issue by Royalgamer06** [jshackles/Enhanced_Steam#1073]
https://steamdb.info/forum/1060/please-add-ingameappid-support-to-the-steamdb-plugin/

I was reading this, and it would be great for enhanced steam. Can you do some magic with this?

**Comment by JoiNNN** [comment]
We used this to make the game name a link to the store page 👍

**Comment by JoiNNN** [comment]
If anyone comes with other suggestions we'll look into it, until then this can be closed.

**Comment by Royalgamer06** [comment]
Well, would you be able to display the hidden games people are playing?
