### ISSUE TITLE
[Suggestion] Allow modifying the number of search results per page.

### ISSUE THREAD

**Issue by Zeturic** [jshackles/Enhanced_Steam#1082]
By default, Steam only shows 25 search results, which is inconveniently small. However, I'm also not a fan of the continuous scrolling of Enhanced Steam for the same reason I don't like it anywhere else; unless you make sure to never close your browser or reload the tab, you can't pick up where you left off.

Would it be possible to increase the number of search results per page? For simplicity, it could be in multiples of 25.

**Comment by VanityFox** [comment]
So, Enhanced Steam is discontinued. There is now [Augmented Steam](https://github.com/tfedor/AugmentedSteam/). Perhaps your requested feature/bugfix is already implemented there! If not, you could move your issue there.
