### ISSUE TITLE
Games titled "Four Pack" etc. recognized by ES as a "four pack" of one game

### ISSUE THREAD

**Issue by RollingStar** [jshackles/Enhanced_Steam#1085]
I've only encountered this with The Pinball Arcade:

http://store.steampowered.com/app/326600

A similar issue occurs on the other season packs. I don't know what a good solution for this would be. You could make a hacky whitelist just for these games that are known to have troublesome titles.

**Comment by peppage** [comment]
I need more information about the issue. Is the issue with the pricing information? If that's true I think this has been fixed and was an issue with isthereanydeal.com

**Comment by RollingStar** [comment]
The issue is still present. I don't think it has to do with Isthereanydeal because it's there before the historical price info loads.

![image](https://cloud.githubusercontent.com/assets/4810902/20552599/999694d2-b11a-11e6-9252-4cad6e1b5e9e.png)

I suspect there's some kind of string comparison going on for the word "Four Pack". But in this case it's a **Season 4 Pack** not a Season **4 Pack**.

**Comment by peppage** [comment]
Thanks!

Yes you are correct it is matching on the words, line 2000,
```javascript
else if (title.contains(' four pack')) { pack_split(this, 4); }
```

Until something else comes up I think we can match on anything with the words season & pack in them.  It really is mostly just the pinball titles.

Here are the list of games with both:

|  id   |  name |
|------|--------|
| 268281 | Pinball Arcade: Season Three Pro Pack|
| 268280 | Pinball Arcade: Season Three Pack|
| 493301 | Pinball Arcade: Season Six Pro Pack|
| 493300 | Pinball Arcade: Season Six Pack|
| 455280 | RaceRoom - WTCC 2015 Season Pack|
| 394561 | Pinball Arcade: Season Five Pro Pack|
| 394560 | Pinball Arcade: Season Five Pack|
| 398915 | Armello - Seasons Board Skins Pack|
| 326600 | Pinball Arcade: Season Four Pack|
| 326610 | Pinball Arcade: Season Four Pro Pack|
| 238273 | Pinball Arcade: Season Two Pro Pack|
| 238272 | Pinball Arcade: Season Two Table Pack|
| 238271 | Pinball Arcade: Season One Pro Pack|
| 238270 | Pinball Arcade: Season One Table Pack|
