### ISSUE TITLE
Remove gradient on Activity page

### ISSUE THREAD

**Issue by mdekleine** [jshackles/Enhanced_Steam#1094]
Please remove the gradient style on games you own \ on your wishlist and just use a colored font. The gradient looks horrible and makes it harder to read (for me at least, i'm colourblind). Or make an option to disable it.

it's the es_highlight_styles style section that is added.

thank you

**Comment by jshackles** [comment]
This is a bug in the current release that's already been fixed in the dev channel.  This will be fixed in stable in the next release, probably within the next 12 hours or so.

**Comment by mdekleine** [comment]
Ah, great and thanks for the quick reply!
