### ISSUE TITLE
Badges page shows incorrect games with cards and card drops remaining

### ISSUE THREAD

**Issue by JohnChristmann** [jshackles/Enhanced_Steam#1111]
I have 0 card drops remaining, and the card value total is correct (showing $0) but it still indicates that I have 1 game with 27 card drops remaining.  Filtering to badges with card drops remaining clears the badge list as expected.  Clearing cached data did not help.

[opera_2016-07-07_12-22-54](https://cloud.githubusercontent.com/assets/17678925/16666719/cdd2d764-443d-11e6-8ed4-f19eb60c6312.png)

**Comment by JoiNNN** [comment]
Not sure what could cause this... I've made a bit of code cleanup in the function responsible for those counts. Until then can you please run this in Chrome's console(to access it press CTRL+SHIFT+I and click Console) and let me know what it outputs:
```
var drops_games = drops_count = 0;
console.log("There are", $J(".progress_info_bold").length, "apps that can have drops");
$J(".progress_info_bold").each(function(i, node) {
  var count = $J(node).text().match(/(\d+)/);

  if (count) {
    console.log("+", i + 1, $J(node).closest(".badge_title_row").find(".badge_title").contents().get(0).nodeValue.trim(), "appears to have drops");
    drops_games = drops_games + 1;
    drops_count += +count[1];
  } else {
    console.log("-", i + 1, $J(node).closest(".badge_title_row").find(".badge_title").contents().get(0).nodeValue.trim(), "doesn't have drops");
  }
});
console.log("Finally, there are", drops_games, "apps with drops, with", drops_count, "cards to drop");
```

**Comment by JohnChristmann** [comment]
There are 29 apps that can have drops
Uncaught TypeError: Cannot read property 'nodeValue' of undefined(…)

Your script appears to be throwing an exception for the first badge on the list, the "Community Ambassador" badge with which I have completed 27 out of 29 tasks.  Enhanced Steam indicates that I have 27 card drops remaining.  Somehow I don't think that's a coincidence.

**Comment by JoiNNN** [comment]
Thanks for looking into it, that seems to be it. I've submitted a fix but I couldn't test fully... If you can test it when it gets approved let us know.

**Comment by JohnChristmann** [comment]
Your fix appears to have worked, thanks for the quick response!  I no longer have 1 extra game and 27 extra card drops listed on my badges page.
