### ISSUE TITLE
Community Market Links Broken for Collector's Items (Team Fortress 2)

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#1122]
View in Community Market Links seem to break at the apostrophe.

Screenshot:
http://i.imgur.com/2hYZDCn.png

Inventory with collector's items for testing this bug:
http://steamcommunity.com/id/SoWhatsNew/inventory/#440

**Comment by fadillzzz** [comment]
Not an issue with the apostrophe, but it's just that there's no such item being sold at the market, so the Steam API simply returns an object stating the request was successful, and there's no price to include in the returned object and Enhanced Steam isn't expecting that, hence, the `undefined` price.

**Comment by Bonsai99** [comment]
I know there is none of that specific item being sold, that wasn't the problem that I was reporting.

The view in community market link breaks after an apostrophe in an item name. I highlighted it in the screenshot. Will update my post to make it more clear.

**Comment by fadillzzz** [comment]
@Bonsai99 Yeah, I noticed that right after I posted my previous comment. Nothing wrong with your post, I was just being stupid that's all :sweat:
