### ISSUE TITLE
Wishlist highlight color blending with price

### ISSUE THREAD

**Issue by Blackbird88** [jshackles/Enhanced_Steam#1131]
![image](https://cloud.githubusercontent.com/assets/4414625/17569241/a616ef74-5f47-11e6-910c-745d82895fc6.png)

**Comment by JoiNNN** [comment]
Some default highlight colors were changed in a recent update, which also addresses this issue by changing the "Wishlist" color to a shade of blue.
I recommend you go into options and reset the color for it, and if it doesn't work for you you can always choose another color you consider fit.

**Comment by Blackbird88** [comment]
Oh. I didn't realize the default color changed. Thanks.
