### ISSUE TITLE
HTTPS Everywhere "breaks" Enhanced Steam in Firefox

### ISSUE THREAD

**Issue by torpet** [jshackles/Enhanced_Steam#1135]
When having HTTPS Everywhere enabled, I get the following error using Enhanced Steam in Firefox 48:

```
One or more requests failed: 

http://api.enhancedsteam.com/storepagedata/?appid=327880&mcurl=http://www.metacritic.com/game/pc/sublevel-zero?ftag=MCD-06-10aaa1f
http://api.enhancedsteam.com/steamapi/GetPlayerSummaries/?steamids=true
http://api.enhancedsteam.com/pricev3/?subs=52659,&stores=steam,amazonus,impulse,gamersgate,greenmangaming,direct2drive,origin,uplay,indiegalastore,gamesplanet,indiegamestand,gog,dotemu,nuuvem,dlgamer,humblestore,squenix,bundlestars,fireflower,humblewidgets,newegg,gamesrepublic,coinplay,funstock,wingamestore,gamebillet,silagames,playfield,imperialgames,&cc=us&appid=327880&coupon=true
```

HTTPS Everywhere probably rewrites the URLs to `https://api.enhancedsteam.com`, as can be seen here: https://www.eff.org/https-everywhere/atlas/domains/enhancedsteam.com.html

Is this an error backendwise or is the HTTPS Everywhere rule invalid?

**Comment by fadillzzz** [comment]
I think you should report this here instead https://github.com/jshackles/Enhanced_Steam_Firefox/issues

**Comment by torpet** [comment]
Done: https://github.com/jshackles/Enhanced_Steam_Firefox/issues/101
