### ISSUE TITLE
2 Whishlist bugs

### ISSUE THREAD

**Issue by SImbiat** [jshackles/Enhanced_Steam#1138]
In Firefox version of the plugin "Early Access" badge is not shown and items can be removed one-by-one (nothing happens when clicking "Remove" link).
Sorry, if this was posted already.

**Comment by fadillzzz** [comment]
Firefox issues should be reported here https://github.com/jshackles/Enhanced_Steam_Firefox/issues

**Comment by SImbiat** [comment]
Posted there.
