### ISSUE TITLE
Profile settings buttons dont work.

### ISSUE THREAD

**Issue by theoddball** [jshackles/Enhanced_Steam#1140]
![](http://i.oddball.tf/rtuDj.gif?raw=true)

**Comment by fadillzzz** [comment]
They're not buttons. You hover over the question mark, and a description should show up.

**Comment by peppage** [comment]
@jshackles I'm working to make this look like the other tooltips but I need to run a function that isn't available yet. I add it to add_es_background_selection but I get an error, "Error in response to storage.get: ReferenceError: BindCommunityTooltip is not defined". Is there a way to run the function on document ready?

**Comment by jshackles** [comment]
@peppage the BindCommunityTooltip function is Valve's.  You'll need to run it in the page context.  For example:

`runInPageContext(function() { BindCommunityTooltip( $J('#element_name') ); });`

All of Enhanced Steam's functionality is already run at $(document).ready

**Comment by peppage** [comment]
hah that's cool. Thanks!
