### ISSUE TITLE
Not showing DRM labels on Mad Max, Deus Ex, etc.

### ISSUE THREAD

**Issue by MadCircus** [jshackles/Enhanced_Steam#1144]
As opposed to most DRM's warnings on the store page, Denuvo drm is not showing for multiple games.
Which I think is very important.
http://pcgamingwiki.com/wiki/The_Big_List_of_3rd_Party_DRM_on_Steam

**Comment by GrandCaptainSpeedyDash** [comment]
I'd like to see something like this implemented as well.

**Comment by 07416** [comment]
I've always wondered how ES gets DRM information in the first place - it's sometimes difficult to figure out if the uses SecuROM, for example.

**Comment by GrandCaptainSpeedyDash** [comment]
Its when Steam doesn't say that a game has DRM or anything like that is when its hard for a consumer to find out.

**Comment by JoiNNN** [comment]
Denuvo DRM warning was added. Can be closed.
