### ISSUE TITLE
steamcommunity automatically jump to https

### ISSUE THREAD

**Issue by wordlesswind** [jshackles/Enhanced_Steam#1155]
http://steamcommunity.com to https://steamcommunity.com
I think this feature is useful.

**Comment by peppage** [comment]
I think this is important but this would force reload the page (after the page has already loaded) and be confusing (and annoying) to the user. Should really let steam handle the http vs https. This should probably be closed.

**Comment by JoiNNN** [comment]
That issue can be solved @peppage, the bigger issue is with Steam not supporting HTTPS entirely...
