### ISSUE TITLE
Mixed Content Errors on Trade Offers and Inventory History Pages

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#1170]
https://steamcommunity.com/my/tradeoffers/
https://steamcommunity.com/my/inventoryhistory/

Screenshots:
http://i.imgur.com/wCmT0Qr.png
http://i.imgur.com/ePK91Ka.png

**Comment by Bonsai99** [comment]
Also happening on profile pages.
https://steamcommunity.com/id/xxBonsai99xx/

Screenshot:
http://i.imgur.com/zknao53.png

**Comment by JoiNNN** [comment]
This is a known issue about which ES can't do much since HTTPS is not fully supported or rather properly supported by the Steam Community or Store. Chances are there will be some broken things also, not just warnings, when force loading pages over HTTPS...
