### ISSUE TITLE
[Feature request] Blackout locked achievements at "Global Gameplay Stats" pages

### ISSUE THREAD

**Issue by thomas-ashcraft** [jshackles/Enhanced_Steam#1173]
There is pages with global achievements stats. Like [this](http://steamcommunity.com/stats/WarThunder/achievements/) or [that](http://steamcommunity.com/stats/CivV/achievements/). And sometimes (even always) its hard to check - which achievements you made and which is not. I found useful for myself simple css3 filter to make a better view of difference between locked and unlocked achievements.

`.achieveRow:not(.unlocked) > .compareImg > img {filter: grayscale(75%) opacity(15%);}`

I would be glad to see that feature in ES as an option.

Without filter (achievements mess):
![fr blackout locked avhievements before](https://cloud.githubusercontent.com/assets/6583664/19424636/8eca5c18-9433-11e6-85c8-1da2d4d21de9.png)

With filter (nice and clean look):
![fr blackout locked avhievements after](https://cloud.githubusercontent.com/assets/6583664/19424647/9a45044e-9433-11e6-98f9-e58bd69c4af6.png)

**Comment by JoiNNN** [comment]
@thomas-ashcraft Looks good. If you have the knowledge, please don't afraid to send a pull request with the changes you want to see in ES, especially when is something this simple, we'll take care of it.
