### ISSUE TITLE
One or more requests failed

### ISSUE THREAD

**Issue by thewierd** [jshackles/Enhanced_Steam#1175]
Error code:

One or more requests failed:
http://api.enhancedsteam.com/early_access/
http://api.enhancedsteam.com/storepagedata/?appid=280160&mcurl=http://www.metacritic.com/game/pc/aragami?ftag=MCD-06-10aaa1f
http://api.enhancedsteam.com/pricev3/?subs=38400,&stores=amazonus,bundlestars,coinplay,direct2drive,dlgamer,dotemu,fireflower,funstock,gamebillet,gamersgate,gamesplanet,gamesrepublic,gog,greenmangaming,humblestore,humblewidgets,imperialgames,impulse,indiegalastore,indiegamestand,newegg,nuuvem,origin,playfield,silagames,squenix,steam,uplay,wingamestore,&cc=SE&appid=280160&coupon=true
http://api.enhancedsteam.com/steamapi/GetPlayerSummaries/?steamids=76561197963698651

**Comment by jshackles** [comment]
The API servers were temporarily unavailable this morning for about 15 minutes due to an unexpected outage.  These errors should no longer be present when browsing Steam.

**Comment by thewierd** [comment]
Had it for 5-10min just when I posted this but now it works.

Thanks mate.
