### ISSUE TITLE
Missing badges sort and view options

### ISSUE THREAD

**Issue by JoiNNN** [jshackles/Enhanced_Steam#1180]
The new "Sort by" and "View" on badges pages are missing when viewing other's profiles.

**Comment by jshackles** [comment]
I don't believe that this functionality has ever existed, but I don't see why it couldn't be adopted with a few modifications.  Filtering options (showing cards with drops remaining) doesn't make sense in this context, nor does sorting by "In progress".  But let me see what I can come up with.

**Comment by JoiNNN** [comment]
Just to clear things up, I was only referring to the sort options available by default and the "Binder view" which can be useful when viewing other profiles. Also the new drop-down design would be nice to have.
I'm also pretty sure that "Binder view" was available before, as I used to test it on other's profiles when I rewrote the way it works.
_Wanted to fix it myself but I don't have much to for coding anymore. I saw you were active recently so I figured might as well open an issue to make sure it doesn't get missed._
