### ISSUE TITLE
can't remove games from wishlist while ES is active

### ISSUE THREAD

**Issue by ahmedtds** [jshackles/Enhanced_Steam#1209]
Enhanced Steam 9.0.2 in Firefox

In wishlist page I can't remove any game from list while ES is active. I can remove them when I deactivated ES so it's clearly a problem with extension.

**Comment by peppage** [comment]
There is a separate firefox repo, check this issue as it might be the same https://github.com/jshackles/Enhanced_Steam_Firefox/issues/85

**Comment by JoiNNN** [comment]
There have been some changes done to how ES 'leaves groups', can you please check if the issue persists?

**Comment by VanityFox** [comment]
So, Enhanced Steam is discontinued. There is now [Augmented Steam](https://github.com/tfedor/AugmentedSteam/). Perhaps your requested feature/bugfix is already implemented there! If not, you could move your issue there.
