### ISSUE TITLE
Early Access banner text malformed

### ISSUE THREAD

**Issue by jshackles** [jshackles/Enhanced_Steam#1223]
As seen here:

![bad](http://abload.de/img/untitled5ougy.png)

The section that says "get instant access..." is not encapsulated, and I believe it's a problem with CSS inheritance.   Can you look into this @JoiNNN ?

**Comment by JoiNNN** [comment]
Is the inclusion of home.css that causes this issue, in customize_app_page() I'm pretty sure. The styles needed for ES will have to be imported and avoid including the whole file.

**Comment by JoiNNN** [comment]
I think this has been fixed by enforcing some additional CSS rules. It can be closed.
