### ISSUE TITLE
[Suggestion] Link to a card's market page to the badge page (+sample code)

### ISSUE THREAD

**Issue by Reassembly** [jshackles/Enhanced_Steam#1228]
Recently, when working on completing card sets, I found myself frequently looking at market pages for cards and then going back to the card's badge page to check my current inventory. I wrote a small Tampermonkey script to make this easier - it just adds a link to market listing pages for trading cards that points to the corresponding badge page (normal or foil as appropriate). I think this would be a convenient addition for enough people that it might merit inclusion into ES.

Here's the userscript I bashed together - it likely won't socket into ES without some modification, but it demonstrates the idea and can be run under Tampermonkey to show the functionality.

```
// ==UserScript==
// @name         Steam Market Badge Link
// @namespace    SteamMarketBadgeLink
// @version      0.1
// @description  Adds links to badge pages for Steam trading card market listings.
// @author       reassembly
// @match        http://steamcommunity.com/market/listings/753/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // calculate components of the badge page URL
    var rootURL = document.body.querySelector("div.playerAvatar > a").getAttribute("href") + "gamecards";
    var jumpIndex = document.URL.match("/[0-9]+(?=-)");
    var cardType = "";
    if(document.URL.endsWith("%20%28Foil%29")) {
        cardType = "?border=1";
       }
    // assemble the URL and insert it as a button into the market listing page
    document.body.querySelector("div.market_listing_nav").innerHTML += "<a target=\"_blank\"  class=\"btn_grey_grey\" href=\"" + rootURL + jumpIndex + cardType + "\">Go to Badge</a>";
})();
```

**Comment by thomas-ashcraft** [comment]
Suggestion implemented. Issue can be closed now.

**Comment by JoiNNN** [comment]
@jshackles can be closed.
