### ISSUE TITLE
Broken in Firefox Developer  [Content Security Policy] Errors

### ISSUE THREAD

**Issue by CrashNBurn71** [jshackles/Enhanced_Steam#1229]
Firefox Developer Edition 52.0a2 (2016-12-11) (64-bit)
> 16:14:58.306 **Content Security Policy:** Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead. (unknown)
16:14:58.733 **Content Security Policy:** The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: onsubmit attribute on DIV element. Enhanced_Steam

No ES features are displayed on any Steam pages.

**Comment by jshackles** [comment]
Please see https://github.com/jshackles/Enhanced_Steam_Firefox/issues/110

**Comment by CrashNBurn71** [comment]
Thank you.  
---
Ah I didn't realize it was a separate Github project. No wonder the references to Firefox was so sparse here.
