### ISSUE TITLE
[Suggestion] Make ES into a steam skin (Possible?)

### ISSUE THREAD

**Issue by DaBomberNTG** [jshackles/Enhanced_Steam#1230]
Like many people, I highly value enhanced steam & want it to improve as much as it can. That said, I find myself going to the desktop app for many things still, including launching games. Which the wed/ES version can't do ( Prove me wrong ;P ), so could most/all of the features be pulled together into a steam skin? I don't know how much a skin can change, but I imagine there are limitations since it is a "Skin".

**Comment by jshackles** [comment]
What Enhanced Steam does cannot be done in a Steam skin.

A few years ago I made a reverse proxy application that could put Enhanced Steam's features into the Steam client, but it became a real support nightmare and was discontinued last year.

http://www.enhancedsteam.com/blog/enhanced-steam-standalone-project-discontinued/
