### ISSUE TITLE
Unable to remove Games/apps from Wishlist

### ISSUE THREAD

**Issue by rohankeluskar1** [jshackles/Enhanced_Steam#1233]
This only seem to happen to the games/apps which have been already removed from steam store.  
I am using chrome Version 55.0.2883.87 m and Enhanced Steam v9.1.1

**Comment by peppage** [comment]
Do you have an example of a game? Can you post a screenshot with no personal information?

Thanks

**Comment by JoiNNN** [comment]
This can be closed. 
_Since this was posted changes and improvements have been made on how items are removed from WL. If the issue persists please open another issue._
