### ISSUE TITLE
Add to Cart button not appearing in wishlist

### ISSUE THREAD

**Issue by RandomHypnotica** [jshackles/Enhanced_Steam#1239]
I found out this was a feature on /r/steam, and yet, I can't see it on my profile and wishlist. I've cleared cache, reset Google Chrome, and re-installed the extension and nothing has appeared.

Currently using Google Chrome Browser, Version 55.0.2883.87 m (64-bit)

Current Installed Extensions

Enhanced Steam V9.1.1
AdBlock 3.8.2
AlienTube for YouTube 2.6
Honey 9.4.4
OG Flickr 1.2
Reddit Enhancement Suite 5.2.2
Search by Image (by Google) 1.5.2
Tumblr Collage 1.4.9

**Comment by jshackles** [comment]
How many items do you have on your wishlist?  

The package data isn't present on this page so Enhanced Steam has to go and pull this from Steam's APIs.  As such, this feature (along with platform info and release date info) is only shown if you have less than 200 items on your wishlist.

**Comment by JoiNNN** [comment]
I'm looking into getting the feature all around.

**Comment by RandomHypnotica** [comment]
> As such, this feature (along with platform info and release date info) is only shown if you have less than 200 items on your wishlist.

That's what's happening here then, I have about 250 or so games on my wishlist.
