### ISSUE TITLE
"Customize" button breaks the homepage in several places

### ISSUE THREAD

**Issue by rahlzel** [jshackles/Enhanced_Steam#1244]
[Unchecking checkboxes in the Customize section](http://i.imgur.com/EfIvkaK.png) causes issues in almost all of those areas after the page is reloaded.

"Steam Controller &": http://i.imgur.com/Xoulntf.png

Not sure what this is: http://i.imgur.com/JQpxup6.png

"Popular" tab: http://i.imgur.com/y9qmtnC.png

Chrome v55
Enhanced Steam 9.1.1

Thanks for this awesome extension!

**Comment by jshackles** [comment]
This is due to the store layout while the sale is going on.  Unfortunately I don't think we'll have another version ready to roll out that could fix this by the time the sale ends.
