### ISSUE TITLE
Dutch translation ready to roll out

### ISSUE THREAD

**Issue by Disgeae** [jshackles/Enhanced_Steam#1251]
Everything in the dutch translation seems to be okay now, just in need of approval to make it 100%!

**Comment by Royalgamer06** [comment]
Mooi. Ik wilde er laatst ook aan gaan werken. 
Helaas antwoorden ze niet veel tickets op het moment.
Ze zijn waarschijnlijk druk.

**Comment by JoiNNN** [comment]
Translations should be done at https://translation.enhancedsteam.com/
Can be closed.
