### ISSUE TITLE
highlighting not working correctly

### ISSUE THREAD

**Issue by skapytek** [jshackles/Enhanced_Steam#1252]
Hello, for me the game highlighting isnt working correctly.
I can add games to my wishlist and when i reload the page i see it highlighted by ES. When i add a game to my "not interested" list and i reload the page its not highlighted. Options are set correctly in the ES addon. Im using ES and Super Steam addon.
Any solution?

regards 
![2017-01-02 22_16_38-steam-suche](https://cloud.githubusercontent.com/assets/11317488/21596264/346139de-d139-11e6-9085-73c867d54040.png)
![2017-01-02 22_18_10-tom clancy s rainbow six siege bei steam](https://cloud.githubusercontent.com/assets/11317488/21596275/75ed1990-d139-11e6-8eac-5b6cd904edf0.png)
![2017-01-02 22_18_48-enhanced steam optionen](https://cloud.githubusercontent.com/assets/11317488/21596278/7aa8f74c-d139-11e6-8aa2-eae7622eef8b.png)

**Comment by jshackles** [comment]
The list of games marked "Not interested" is captured from the Steam store's dynamic apps API and then cached by Enhanced Steam.  I've seen before where this API can take hours to update for users, sometimes days in some extreme cases - this is on Valve's end.  Once their API updates with your correct apps, you'll either need to wait for Enhanced Steam's cache to expire (a few hours) or use the menu at the top of the page to clear your cache manually.

**Comment by JoiNNN** [comment]
This should be fixed now since we update the cache with almost every change to the wishlist and 'not interested' list.
