### ISSUE TITLE
[suggestion] Automatically expand all panels on wishlist

### ISSUE THREAD

**Issue by BlivetWidget** [jshackles/Enhanced_Steam#1263]
For purposes of always finding the lowest price, it would be nice if the game 'panels' on the wishlist were always expanded to show current and historical lowest price, rather than requiring a mouse hover.

This would not only save time during a manual search, but would allow page-watching extensions to find when a game has gone on sale on another site.

**Comment by jshackles** [comment]
The reason this is done on hover (rather than all at once) is because some people have wishlists with thousands of games in them, and loading that data all at once would cause quite a bit of strain on our servers.

**Comment by BlivetWidget** [comment]
Fair enough, there's some pretty extreme edge-cases out there.

I didn't realize your servers handled fetching the current lowest price, I figured the extension did the work client-side.  Though I guess that would put a lot more load on your information sources (isthereanydeal, etc).  I guess it makes the most sense to create a waitlist on isthereanydeal.  Right-o, thanks for your time!  Your extension is still quite an improvement on Steam.

**Comment by JoiNNN** [comment]
Can be closed.
