### ISSUE TITLE
[Bug] Steam community does not work.

### ISSUE THREAD

**Issue by BarterClub** [jshackles/Enhanced_Steam#1264]
When enhanced steam is on all community features say error like this one; "There seems to have been an error saving your review. Please try again later." When i disable enhanced steam it works again. Not sure what is going on.

**Comment by jshackles** [comment]
Did this happen just now, or has it been an ongoing issue for some time?

Steam is currently undergoing website maintenance that causes intermittent issues such as this regardless of whether or not you're using Enhanced Steam.

**Comment by BarterClub** [comment]
This has been happening right after the winter sale. Not sure if steam changed some things around.

**Comment by BarterClub** [comment]
Ok figured it out. It was do to google's data saver extension. Somehow the extension was messing up steam.

Thanks for helping.
