### ISSUE TITLE
[Suggestion] Wish List sorted by review score

### ISSUE THREAD

**Issue by screwyluie** [jshackles/Enhanced_Steam#1265]
Seems like it would be a good idea to sort a long wish list by review score. Both options would be nice (recent and over all) since steam has two scores now. 

As a side note it might be good to have the review scores visible for items on the wish list, if not on the default bar perhaps in the pop-under/expansion you get when you mouse over them.

**Comment by jshackles** [comment]
We are looking into adding this functionality, but currently review scores are not accessible from that page.  This means Enhanced Steam will need to do obtain that data either from Steam's API or the Enhanced Steam API.  The Steam API lists the number of reviews, but unfortunately does not display any other relevant data such as the number of positive reviews that could be used to get any worthwhile data.

This is an oft-requested feature though, and I think it's possible it's just going to take a little heavy lifting on our server's part, stay tuned.

**Comment by JoiNNN** [comment]
Feature added, can be closed.
