### ISSUE TITLE
[Suggestion] Remove links on profiles for AStats.nl

### ISSUE THREAD

**Issue by CptBrian** [jshackles/Enhanced_Steam#1266]
You already have a link for AchievementStats.com, which is a fine alternative to this site that flags tons of profiles for "using an achievement hack" even if they haven't. Their detection for it is wildly inaccurate(and it can never _be_ accurate), and they want you to manually request removal of the flag by making a forum thread and admitting to something you didn't do, _and_ they want you to remove achievements you earned legitimately by using third-party software.. but you can't be upset at them about them wrongfully flagging your profile, no.. they want you to suck their dick while the power-tripping teenagers act like nothing went wrong.
Nothing like being called a cheater when you work hard for what you got. I obviously don't like them and wouldn't like anyone else to have to deal with their bullshit. I've noticed profiles of friends also being flagged wrongfully. They're refusing to remove my profile too, because they're dickheads.
I wouldn't have even known about the site if it weren't for Enhanced Steam, so that's why I came here. Also, do you know of any way I can report them to Valve to get them to remove my profile, or what I can do to help this?

**Comment by jshackles** [comment]
Sorry you had a bad experience.  The profile link for any site can be turned off in the extension's option page which is accessible using the menu at the top of each Steam page.

As long as your Steam profile is public, sites such as this one can access your gameplay stats, even without your express consent.  You would [need to contact the site directly](http://astats.astats.nl/astats/Contact.php) to ask them to remove your information.
