### ISSUE TITLE
[BUG] Enchanced Steam is not working at store.steampowered.com

### ISSUE THREAD

**Issue by FoX-Sempai** [jshackles/Enhanced_Steam#1269]
Enchanced Steam is not working at store.steampowered.com and works perfectly fine at http://steamcommunity.com/. What could it be?
Im using Google Chrome 55.0.2883.87 m, Windows 7 x64 Ultimate.
Thanks in advance!

**Comment by BarterClub** [comment]
Try deleting the extension and reinstalling, that might help.

**Comment by FoX-Sempai** [comment]
Already done that. Doesn't help :(.

**Comment by jshackles** [comment]
If you press F12 and view the console, are you getting any error messages?

**Comment by FoX-Sempai** [comment]
Yes. there is.

Here:

`include.preload.js:468 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
createShadowTree @ include.preload.js:468
ElemHide @ include.preload.js:435
(anonymous) @ include.preload.js:587
enhancedsteam.js:4  Enhanced Steam v9.1.1 by jshackles  http://www.enhancedsteam.com 
enhancedsteam.js:213 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'unUserdataVersion' exceeded the quota.
    at setValue (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:213:15)
    at chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:189:4
    at chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:196:3
setValue @ enhancedsteam.js:213
(anonymous) @ enhancedsteam.js:189
(anonymous) @ enhancedsteam.js:196
enhancedsteam.js:213 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'dynamicstore_data' exceeded the quota.
    at setValue (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:213:15)
    at Object.<anonymous> (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:178:6)
    at i (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:27449)
    at Object.fireWith [as resolveWith] (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:28213)
    at y (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4:22721)
    at XMLHttpRequest.c (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4:26925)
setValue @ enhancedsteam.js:213
(anonymous) @ enhancedsteam.js:178
i @ jQuery.min.js:2
fireWith @ jQuery.min.js:2
y @ jQuery.min.js:4
c @ jQuery.min.js:4`

http://i.imgur.com/CyB6T3n.png

**Comment by JoiNNN** [comment]
@FoX-Sempai try clearing ES's cache.

**Comment by FoX-Sempai** [comment]
Im sorry, but how?

**Comment by JoiNNN** [comment]
At the top of the page in ES's menu ![dzfsf](https://cloud.githubusercontent.com/assets/3322834/21965235/830c4594-db64-11e6-9953-c3e7356f6125.png)

**Comment by FoX-Sempai** [comment]
there is no such button at store.steampowered.com :(

**Comment by JoiNNN** [comment]
Oh, forgot about that =) open the console as Jason told you before, paste this `localStorage.clear();` and hit enter.

**Comment by FoX-Sempai** [comment]
> undefined

**Comment by JoiNNN** [comment]
That's expected, try refreshing the page and see if it works.. also check the console for other errors.

**Comment by FoX-Sempai** [comment]
hm... you know, it works o_O no any other errors, just one warning

**Comment by FoX-Sempai** [comment]
Thanks a lot!

**Comment by JoiNNN** [comment]
Glad you got it working.
