### ISSUE TITLE
[BUG] "Submit Your Time" link to howlongtobeat.com not working

### ISSUE THREAD

**Issue by M-Z-2017** [jshackles/Enhanced_Steam#1273]
The link is currently redirecting to
https://howlongtobeat.com/submit_add.php?gid=1234
which does not work anymore.

The correct link is
https://howlongtobeat.com/submit.php?s=add&gid=1234

**Comment by jshackles** [comment]
Thanks for the heads up.  Because this value is returned server-side, this issue has been corrected without the need to change any client-side code.

It should work correctly now.
