### ISSUE TITLE
Steam account hijacked after installing Enhanced Steam

### ISSUE THREAD

**Issue by Xodetaetl** [jshackles/Enhanced_Steam#1276]
Installing Enhanced Steam is the only thing special I remember doing in the last days, before my account was stolen. Is it possible at all for someone to get access to login information through this plugin?

**Comment by JoiNNN** [comment]
I doubt it, ES by default is completely disabled on all login pages.

**Comment by CrazyIvanTR** [comment]
ES only works in store pages where there is no SSL (afaik), this shouldn't be an issue.

**Comment by jshackles** [comment]
Enhanced Steam does not store, intercept, or transmit your personal account details or information.  As others have said, it's specifically disabled on all login and checkout pages.

If you installed Enhanced Steam from an official source such as www.EnhancedSteam.com or this repository, then it could not have been the cause of your account being stolen.

**Comment by Xodetaetl** [comment]
Thanks for your answers
