### ISSUE TITLE
Permalink on sidebar next to SteamRep reputation links to wrong profile

### ISSUE THREAD

**Issue by rvaidya** [jshackles/Enhanced_Steam#1286]
The impersonator's profile shows my permalink with SteamID64, not his.

Impersonator profile:

http://steamcommunity.com/profiles/76561198201205038

My profile:

https://steamcommunity.com/profiles/76561197980236300

Picture: http://imgur.com/a/wuvyn

**Comment by jshackles** [comment]
The permalink in your picture was not placed there by Enhanced Steam.  Enhanced Steam places your permalink in a box below that whick makes it easier to copy.

You'll need to identify the offending extension and take the issue up with them.

**Comment by rvaidya** [comment]
Ah sorry, must be Steam Inventory Helper.  Thanks for the quick response.
