### ISSUE TITLE
please bring back cd keys

### ISSUE THREAD

**Issue by cms2k1** [jshackles/Enhanced_Steam#1287]
ive been having many issues with uplay and third party applications and their dlc. you need a cd key to be able to add dlc to the game, you cant just use steam to acces the dlc for watchdogs 2. ive had many problems not having a cd key and there was no reason to take it out

**Comment by jshackles** [comment]
You will need to direct this to Steam Support at https://help.steampowered.com/ as this issue has nothing to do with Enhanced Steam.
