### ISSUE TITLE
[Suggestion] Skip "You are leaving Steam" page

### ISSUE THREAD

**Issue by BarterClub** [jshackles/Enhanced_Steam#1302]
Not have this pop up or skip this part of the site.

![steam](https://cloud.githubusercontent.com/assets/10663563/22622572/af0ce0c0-eaf2-11e6-82f0-464ddf1b843d.PNG)

Thanks

**Comment by JoiNNN** [comment]
The feature is already in ES. Options > Community > Disable confirmation when accesing external sites

**Comment by BarterClub** [comment]
i am sorry that i missed that. Well then. Thanks for telling me where it was.
