### ISSUE TITLE
Firefox Multiprocess Support

### ISSUE THREAD

**Issue by szymonszydelko** [jshackles/Enhanced_Steam#1307]
Hello.
Would a conversion of ES to the Firefox multiprocess infrastructure be possible? As far as I know the API is very Chrome-like.
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Adapting_to_Multiple_Processes

**Comment by jshackles** [comment]
The Firefox version of Enhanced Steam already uses their WebExtensions APIs and therefore already has Multiprocess support.  You can download the latest version from the Enhanced Steam website.
