### ISSUE TITLE
The link to steamdb is strange in the product page treated as 'sub'

### ISSUE THREAD

**Issue by Gockey** [jshackles/Enhanced_Steam#1310]
The appID is an illegal string "[object Object]".
Is it only my environment?

![fx51_enhancedstam_steamdb_link_in_sub](https://cloud.githubusercontent.com/assets/26034108/23336644/47f9ac28-fc19-11e6-81ee-5ce1f024cc3f.png)

**Comment by peppage** [comment]
Might be something in just the firefox version which has its issues tracked here https://github.com/jshackles/Enhanced_Steam_Firefox

**Comment by shenxufeng** [comment]
The same problem and they have not fixed it...

**Comment by peppage** [comment]
In chrome? I would fix it but I haven't been able to replicate it. Any more details you can add so that I can replicate and fix it?

**Comment by JoiNNN** [comment]
Happens only in FF. I made a quick debug in console but nothing strange came up. Feel free to debug further, I hate FF nowadays and won't bother unless I really have to..

**Comment by shenxufeng** [comment]
Sorry I didn't make it clear. Yes, I use a Chrome version. Every SteamDB link of a SUB on a Steam Store page is "http://steamdb.info/sub/[object%20Object]/". It's a wrong link and I need to copy sub to replace "[object%20Object]".

![steamdb_sub_link](https://cloud.githubusercontent.com/assets/10850767/23892412/6d3a3200-08d5-11e7-8311-f830e93ce0ab.jpg)

**Comment by JoiNNN** [comment]
Hmmm.. if this happens in Chrome too it be related so some setting. @shenxufeng can you please go to this sub http://store.steampowered.com/sub/50292/,  open the console (F12), select Enhanced Steam for execution (this is important, see the screenshot) then execute this code and let me know what it outputs
```
var path = window.location.pathname.replace(/\/+/g, "/");
console.log(window.location.host, path, get_subid(window.location.host + path));
```
![essssssssss](https://cloud.githubusercontent.com/assets/3322834/23913220/ebaf601e-08ea-11e7-9d26-864eae0af5ac.png)

**Comment by shenxufeng** [comment]
@JoiNNN Thank you for your help! I have done it and here are outputs:

`store.steampowered.com /sub/50292/ Object {}
undefined
jQuery.min.js:4 GET http://store.steampowered.com/api/appdetails/?appids=store.steampowered.com/sub/50292/ 400 (Bad Request)`

**Comment by shenxufeng** [comment]
Thanks!

**Comment by JoiNNN** [comment]
@jshackles can be closed.

**Comment by JoiNNN** [comment]
@jshackles @gockey this can be closed.
