### ISSUE TITLE
[BUG] Conflict with HTTPS Everywhere extension 

### ISSUE THREAD

**Issue by nickpreveza** [jshackles/Enhanced_Steam#1319]
Disabling the extension fixed any issues

Error Message:

Failed Requests:
http://api.enhancedsteam.com/storepagedata/?appid=396280&r_all=30&r_pos=26&r_stm=24&mcurl=http://www.metacritic.com/game/pc/anarchy-online?ftag=MCD-06-10aaa1f&oc
http://api.enhancedsteam.com/pricev3/?subs=&stores=amazonus,bundlestars,coinplay,direct2drive,dlgamer,dotemu,fireflower,funstock,gamebillet,gamersgate,gamesplanet,gamesrepublic,gog,greenmangaming,humblestore,humblewidgets,imperialgames,impulse,indiegalastore,indiegamestand,newegg,nuuvem,origin,playfield,silagames,squenix,steam,uplay,wingamestore,&cc=GR&appid=396280&coupon=true

**Comment by develop7** [comment]
Affects me too, here are logs from console:

```
 Enhanced Steam v9.2 by jshackles  http://www.enhancedsteam.com 
(index):1 Refused to connect to 'https://api.enhancedsteam.com/early_access/' because it violates the following Content Security Policy directive: "connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://localhost:27060 http://steamcommunity.com/ https://steamcommunity.com/".

chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:567 Uncaught TypeError: Cannot read property 'failed' of undefined
    at Object.<anonymous> (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:567)
    at i (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2)
    at Object.fireWith [as rejectWith] (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2)
    at y (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4)
    at XMLHttpRequest.c (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4)
(index):1 Refused to connect to 'https://api.enhancedsteam.com/storepagedata/?appid=505230&oc' because it violates the following Content Security Policy directive: "connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://localhost:27060 http://steamcommunity.com/ https://steamcommunity.com/".

(index):1 Refused to connect to 'https://api.enhancedsteam.com/pricev3/?subs=&stores=amazonus,bundlestars,co…silagames,squenix,steam,uplay,wingamestore,&cc=BY&appid=505230&coupon=true' because it violates the following Content Security Policy directive: "connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://localhost:27060 http://steamcommunity.com/ https://steamcommunity.com/".

(index):1 Refused to connect to 'https://api.enhancedsteam.com/acrtag/' because it violates the following Content Security Policy directive: "connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://localhost:27060 http://steamcommunity.com/ https://steamcommunity.com/".

(index):1 XMLHttpRequest cannot load https://steamcommunity.com/actions/GetNotificationCounts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```

**Comment by mvicari** [comment]
Same here.

Image [here](http://imgur.com/a/ZNfqX).

**Comment by tehcojam** [comment]
Now Steam has enabled [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

**Comment by FlaminSarge** [comment]
Seems like disabling HTTPS Everywhere for the 'Enhancedsteam.com' entry while on the Steam website fixes this. It could be that the Enhanced Steam website enabled CSP or something.

**Comment by develop7** [comment]
> It could be that the Enhanced Steam website enabled CSP or something.

Nope, it's Steam:
<details><summary> See Content-Security-Policy's connect-src </summary>
```
$  curl -v 'http://store.steampowered.com/app/340000' > /dev/null
* TCP_NODELAY set
* Connected to store.steampowered.com (104.86.35.20) port 80 (#0)
> GET /app/340000 HTTP/1.1
> Host: store.steampowered.com
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache
< Expires: Mon, 26 Jul 1997 05:00:00 GMT
< Cache-Control: no-cache
< Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' http://store.akamai.steamstatic.com/ https://steamstore-a.akamaihd.net/ *.google-analytics.com https://www.gstatic.com; object-src 'none'; connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://localhost:27060 http://steamcommunity.com/ https://steamcommunity.com/; frame-src 'self';
< X-Frame-Options: DENY
< Content-Type: text/html; charset=UTF-8
< X-Varnish: 1500401221
< Date: Tue, 21 Mar 2017 20:25:49 GMT
< Transfer-Encoding:  chunked
< Connection: keep-alive
< Connection: Transfer-Encoding
```
</details>

**Comment by anthonypants** [comment]
The title of this bug should be changed from "Conflict with HTTPS Everywhere extension" to "Conflict with HTTPS" or similar.

**Comment by sleeksorrow** [comment]
@anthonypants: IMHO the title should not be changed. While you are right, the https conflict only apears when using HTTPS Everywhere Addon. Without this addon, you never run into this conflict as far as I understood the problem.

Workaround: While on steam, click the HTTPS Everywhere icon and deselect just the usage for enhancedsteam.com. This way you won't loose the HTTPS Everywhere security benefits on other pages.

![spectacle z14679](https://cloud.githubusercontent.com/assets/390307/25196459/105b856a-2541-11e7-9ba6-434aae258e17.png)

**Comment by FlaminSarge** [comment]
^I've had this work before, but at some point it stopped working, and I'm not sure why. Will try to gather more information.

**Comment by DFNCTSC** [comment]
@jshackles Can we get a quick fix for this HTTPS-related issue? Has existed for several months now and should be easily fixed with a single value change (possibly even just the addition of one letter). <3
