### ISSUE TITLE
[Suggestion] Add an option to show a link to rep.tf on a user's profile

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#1321]
Show's a user's ban status on a variety of different websites like tf2outpost, backpack.tf, etc. as well as Steamrep in a single location. 

Helpful in avoiding users that trade with scammers and are banned on backpack and/or outpost but are not tagged on Steamrep.

**Comment by JoiNNN** [comment]
Users can now add custom sites links.
This can be closed.
