### ISSUE TITLE
Enhanced Steam is inaccessible for me due to a stupid law

### ISSUE THREAD

**Issue by FosumFox** [jshackles/Enhanced_Steam#1331]
Hi, not necessary an issue related to the tool itself, but the website not being able to load anything due to a stupid law in Russia, an organization that works for making internet a safe place by blocking sites that host illegal, "bad" for children stuff and related to that, some specific ISPs (such as mine) block not only the domain, but the whole IP of that domain, making other sites hosted on Cloudflare inaccessible and that's what happened here as well. Is there anything you could do to fix this little problem by switching IPs, perhaps? I really liked using Enhanced Steam, and sadly no, changing ISP is not an option for me either.

**Comment by spannerman79** [comment]
I suggest that you use a VPN.  I doubt that Cloudflare will be dumped due to what Cloudflare actually does just for someone that can fix it on their end with a VPN.

Non-issue

**Comment by FosumFox** [comment]
I suggest not dumping Cloudflare completely, but at least shuffle to different IP's that aren't blocked, at least. Also using VPN isn't really an optimal solution since I'm always getting logged off each time I change my IP like that and it isn't worth the time and effort just to load all the data and prices like that.

**Comment by spannerman79** [comment]
> I'm always getting logged off each time I change my IP like that

That is normal

> and it isn't worth the time and effort just to load all the data and prices like that.

I use a VPN about 80% of the time.  Even more so when I travel

> I suggest not dumping Cloudflare completely, but at least shuffle to different IPs that aren't blocked

Did you even bother to check Cloudflare's system? Or know what CIDR's actually are?  Cloudflare more then likley is limited to the CIDR's that it has allocated which more then likley are blocked in your country.

**Again** as I stated before - use a VPN
