### ISSUE TITLE
[BUG] Trading card market link not working

### ISSUE THREAD

**Issue by kennyboy55** [jshackles/Enhanced_Steam#1340]
Market links are not working for cards which have an apostrophe in their name. See image.

![chrome_2017-04-17_6ratg](https://cloud.githubusercontent.com/assets/9005391/25102574/4780e76c-23b9-11e7-9e17-07eb91eb996b.png)

**Comment by JoiNNN** [comment]
Thank you for reporting, the bug is fixed in PR #1342 and should be available in the next release.
