### ISSUE TITLE
[Suggestion] Ability to add comments to games on wishlist

### ISSUE THREAD

**Issue by drewhill** [jshackles/Enhanced_Steam#1349]
I save tons of games to my wishlist, and I would love to be able to store comments on them, viewable on the wishlist -- mostly just to remind myself what price I would be willing to buy them at or why it is that I am interested in them.

**Comment by chrisblakley** [comment]
Unless I'm misunderstanding this request, this feature already exists. In your wishlist, you can click the dropdown on one of the games and you'll see "Wishlist Note".

**Comment by drewhill** [comment]
You're totally right; I've never even noticed that drop-down before. Thank you!
