### ISSUE TITLE
Unknown issues

### ISSUE THREAD

**Issue by ScoobyJD** [jshackles/Enhanced_Steam#1359]
Thought I would present these I have noticed for some time now.
![enhancedsteam](https://cloud.githubusercontent.com/assets/5624644/26532398/dccfd16e-43cd-11e7-9384-1719d9599cbd.jpg)

**Comment by jshackles** [comment]
Are you using HTTPS Everywhere?  This is a possible duplicate of #1319

**Comment by ScoobyJD** [comment]
Yes, I am. Should I disable it for steam?

**Comment by ScoobyJD** [comment]
Confirmed that disabling fixes the problem as stated in duplicate. Thanks! Didn't understand what all that code meant. Noob out :-( lol
