### ISSUE TITLE
Historical Lowest Price lists EA's "Origin" platform as "Origin PC"

### ISSUE THREAD

**Issue by lib2k** [jshackles/Enhanced_Steam#1362]
![poop](https://user-images.githubusercontent.com/17688383/26845271-459c9810-4af6-11e7-805a-2241894fc61a.png)

Meanwhile "Origin PC" is actually a custom PC manufacturer and has nothing to do with EA.  
http://www.originpc.com
  
Kinda confusing.

**Comment by seeeeew** [comment]
That's how [IsThereAnyDeal.com](http://isthereanydeal.com) returns it. You should ask them to change it.
