### ISSUE TITLE
[Maybe a BUG?]Cannot show "Install Steam" button correctly

### ISSUE THREAD

**Issue by zly926** [jshackles/Enhanced_Steam#1363]
I'm pretty sure that I didn't tick the "Hide 'Install Steam' button" option, but everytime I refresh the page, the "Install Steam" button just flash and disappeared, then replaced by the drop-down menu of Enhanced Steam.
This bugged me pretty hard, and I don't know why this is happening.

**Comment by zly926** [comment]
Here's the screenclip.
![image](https://user-images.githubusercontent.com/16865501/26961481-92ed5f10-4d11-11e7-8d62-1a214cb02253.png)

**Comment by Connor37** [comment]
Cannot reproduce.

**Comment by JoiNNN** [comment]
```I'm pretty sure that I didn't tick the "Hide 'Install Steam' button" option```
Can you please check again? And also disable other extensions.

**Comment by zly926** [comment]
I found out where the problem is......There's another checkbox for the "Install Steam" in _Steam Database_
![image](https://user-images.githubusercontent.com/16865501/27035069-91ea133a-4fb2-11e7-88e2-c444b75b8073.png)
I ticked it off and the button was back!
Thans for reply and sorry to interrupt.
