### ISSUE TITLE
[BUG] Dynamic wishlist sorting interferes with ranking

### ISSUE THREAD

**Issue by seeeeew** [jshackles/Enhanced_Steam#1380]
When the wishlist was sorted by rank on page load and the sorting is dynamically switched to something else, items can still be rearranged, which messes up the ranking.

When the wishlist wasn't sorted by rank on page load and the sorting is dynamically switched to "Rank", items still can't be rearranged.

**Comment by JoiNNN** [comment]
Hmm... I see you point, and although not intended one could use this to rank and save it's WL order by review scores or names  for eg.

We can address the issue at hand by simply not updating the ranks anymore if order by rank is not currently active, it can be done by setting ```g_bRankMode = false;```

**Comment by seeeeew** [comment]
Nice timing! :smile:

**Comment by JoiNNN** [comment]
Just found this #646. Maybe we can add a "Rank in this order" button in the future, something like this 
![rrrr](https://user-images.githubusercontent.com/3322834/27997774-24ce4f58-6508-11e7-99d5-503071d0003f.png)

**Comment by seeeeew** [comment]
Sure, why not, if people want it. I'll add further comments to #646, since it doesn't really fit here if there's a more fitting issue.
