### ISSUE TITLE
[BUG] Store displays not working (prices, benchmark data, etc...)

### ISSUE THREAD

**Issue by Omarock92** [jshackles/Enhanced_Steam#1396]
![untitled](https://user-images.githubusercontent.com/23641366/27997069-896099ac-64f0-11e7-82d3-f6019fc8f308.jpg)

**Comment by Omarock92** [comment]
It seems to be fixed.

**Comment by seeeeew** [comment]
Looks like the ES API server was temporarily unavailable. Can you close this issue (with the grey button at the bottom)?
