### ISSUE TITLE
[BUG] Error When Relisting Market Items

### ISSUE THREAD

**Issue by SwiftBoyAdams** [jshackles/Enhanced_Steam#1407]
![enhanced steam error](https://user-images.githubusercontent.com/20410015/28627216-0f4c4554-7219-11e7-922e-c915dec9a588.PNG)

On the Market page, if I click the Remove link for a sell listing and then the Edit Price button and then amend the price, I receive the error in the screenshot: "The item specified is no longer in your inventory or is not allowed to be traded on the community market."  I also get the same error if I go to the individual item's page and try to edit the price of my sell listing from there.

This only started happening today. If I go to my Inventory and manually relist the item, it works fine. Using "Quick Sell" from the Inventory works fine too.

I've tried clearing the Enhanced Steam cache and resetting Chrome. I'm not running any other extensions.

**Comment by SwiftBoyAdams** [comment]
Looks like Valve released a change to Steam on the day this problem started occurring. Whatever they changed seems to have broken this functionality in ES. I can get round the issue for now by manually relisting items.

**Comment by JoiNNN** [comment]
Can be closed, since the feature was removed from ES.

**Comment by jshackles** [comment]
Yes unfortunately this can't be reliably fixed due to the new API constraints.  :crying_cat_face:

**Comment by SwiftBoyAdams** [comment]
​That's a shame. Never mind, the workaround isn't too onerous.

Thank you for investigating and for updating me. Looks like there's some
​nice new features in the latest ES. Thanks for all your hard work.
