### ISSUE TITLE
The French strings to filter search on the Steam store are bugged

### ISSUE THREAD

**Issue by woctezuma** [jshackles/Enhanced_Steam#1417]
The search filter has been bugged for the French store for a while now.

It looks like the strings are too long to be displayed and are replaced by three dots instead.

![English Store](https://i.imgur.com/psQNzjs.png) ![French Store](https://i.imgur.com/m0Y0AAi.png)

Moreover, there should not be an "s" at the end of "coûtant".

**Comment by seeeeew** [comment]
You can propose better translations on [translation.enhancedsteam.com](http://translation.enhancedsteam.com/translate/enhanced-steam/4/en-fr).
