### ISSUE TITLE
[BUG]Extended wallet info not loading

### ISSUE THREAD

**Issue by AkiraJkr** [jshackles/Enhanced_Steam#1422]
http://i.imgur.com/dcx9Lwm.png

I don't know if it's my fault, but here it is.

It was supposed to become something like this: https://cdn.discordapp.com/attachments/293945389277773834/351060200263778324/unknown.png

**Comment by VanityFox** [comment]
So, Enhanced Steam is discontinued. There is now [Augmented Steam](https://github.com/tfedor/AugmentedSteam/). Perhaps your requested feature/bugfix is already implemented there! If not, you could move your issue there.

**Comment by AkiraJkr** [comment]
This is super old and has been fixed a LONG time ago.
