### ISSUE TITLE
[BUG] Enhanced Steam automatically expands to show all games in the Community Market

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#1433]
Was recently updated to only show the most popular, with the option to show the others by clicking show more.

https://www.reddit.com/r/Steam/comments/6yfwok/steam_community_market_now_has_an_expandable_list/

Enhanced Steam seems to automatically expand this list.
https://i.imgur.com/ogdcaIX.png
https://i.imgur.com/CMJOh0k.png

**Comment by jshackles** [comment]
Thanks for the heads up, I will look into fixing this for the next release.
