### ISSUE TITLE
[BUG] "Submit Your Time" for HLTB broken

### ISSUE THREAD

**Issue by seeeeew** [jshackles/Enhanced_Steam#1453]
The _Submit Your Time_ link for [How Long To Beat](https://howlongtobeat.com/) doesn't work anymore. Seems like the API changed.

**Comment by seeeeew** [comment]
Seems this needs to be fixed server side. `hltb.submit_url` in the JSON data returned by the ES _storepagedata_ API should be changed to `https://howlongtobeat.com/submit.php?s=add&gid=<ID>`.

**Comment by jshackles** [comment]
This should be working correctly again now - thanks for the heads up.

**Comment by seeeeew** [comment]
Works fine now! :+1:
