### ISSUE TITLE
Steam store button in wishlist

### ISSUE THREAD

**Issue by XYUSoma** [jshackles/Enhanced_Steam#1463]
I'm using Google Chrome and I have 943 items on my wishlist. Since yesterday, I no longer see a Steam store button on any of the items on my wishlist. I never happened before.

Thank you

**Comment by jshackles** [comment]
Please review the application changelog.  These buttons were removed and were replaced with making the game names as clickable links.  This is by design.

**Comment by XYUSoma** [comment]
OK thank you.
