### ISSUE TITLE
[BUG] Duplicate wallet balance shown on steamcommunity pages

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#1464]
Valve now shows wallet balance on community pages making the "Show steam wallet funds in header" option no longer necessary and having it enabled will show your balance twice.

![chrome_2017-10-25_15-43-11](https://user-images.githubusercontent.com/11639363/32019758-36c5e002-b99c-11e7-9a02-35fad3947c33.png)
![chrome_2017-10-25_15-50-45](https://user-images.githubusercontent.com/11639363/32019830-65411fdc-b99c-11e7-9e97-a07348ffadfb.png)

**Comment by lachlancooper** [comment]
This was fixed in dev 40acdf19def196ab467bf63873b42ec18c2d9073.
