### ISSUE TITLE
[BUG] Activate Multiple Products

### ISSUE THREAD

**Issue by Raykay101** [jshackles/Enhanced_Steam#1465]
https://store.steampowered.com/account/registerkey

When trying to use the feature "Activate Multiple Products", it says "An error has occurred". Even trying to activate a product one-by-one does not work. Thankyou for reading my message.

**Comment by dbrereton1995** [comment]
Both activating a single and multiple key/s works fine for me (64-bit Win10 / Chrome). Try reinstalling the extension.

**Comment by Raykay101** [comment]
I'm using 64-bit Windows 10 on the latest version of Chrome. Reinstalling Enhanced Steam resolved the issue thanks!
