### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by DraxxorT** [jshackles/Enhanced_Steam#1466]
The newest update caused prices from alternate stores to display incorrectly. See screenshot:

![enhanced steam display problem](https://user-images.githubusercontent.com/32966434/32134421-6c3a5dd4-bbaa-11e7-954d-219b5f99cc67.jpg)

**Comment by jshackles** [comment]
If you're talking about all those green buttons - those aren't a feature of Enhanced Steam and are probably being added by another extension or addon.

**Comment by DraxxorT** [comment]
I'm sorry; you're correct. That's from Steam Snipe. I'm not sure why it doesn't want to play nice with Enhanced Steam anymore, but the display error started happening with the latest ES update, so I assumed it was an ES feature. Not your problem, though. Thanks for the response.
