### ISSUE TITLE
[BUG] Transparent price comparison

### ISSUE THREAD

**Issue by mpostument** [jshackles/Enhanced_Steam#1481]
Hello,

Sometimes i am see transparent windows with prices, and it is not possible to see prices
And i haven't found where i can disable this
![hollow](https://user-images.githubusercontent.com/9252594/32774116-f6cbcf32-c933-11e7-948f-d12fba2750a1.jpg)

**Comment by Darius-bd** [comment]
Same here, highly annoying. I'd say the problem is with the layering of the price element.

**Comment by VanityFox** [comment]
So, Enhanced Steam is discontinued. There is now [Augmented Steam](https://github.com/tfedor/AugmentedSteam/). Perhaps your requested feature/bugfix is already implemented there! If not, you could move your issue there.
