### ISSUE TITLE
[BUG] Available money displayed twice on community pages

### ISSUE THREAD

**Issue by lainverse** [jshackles/Enhanced_Steam#1484]
Might be related to the new UAH ( ₴ ) currency.
Visit any community page. Here is my profile: http://steamcommunity.com/id/lainverse/
Screenshot of the issue:
![steamcommunity com_id_lainverse_](https://user-images.githubusercontent.com/4563325/32839473-3c212ea8-ca1d-11e7-8c5f-17acb4839298.png)

**Comment by rluik** [comment]
Duplicate of #1464

**Comment by lainverse** [comment]
As I understand fix is not released yet since there is still an option to show/hide balance in 9.6. On the other hand now I know there is an option for that. So, I close it then.
