### ISSUE TITLE
itch.io mismatches

### ISSUE THREAD

**Issue by ScottKillen** [jshackles/Enhanced_Steam#1495]
Enhanced Steam is reporting $0.00 for Tree of Life on itch.io--however, this is a very early alpha that was being given away before the game appeared on Steam.

**Comment by KarlCastle** [comment]
The prices and price history shown are taken from https://isthereanydeal.com/

Their issue tracker has a report for the mismatch (two different games with the same name): https://bitbucket.org/tfedor/isthereanydeal.com/issues/875/tree-of-life-has-the-wrong-itchio-game and when ITAD fixed the mismatch, Enhanced Steam will reflect the correct price.

**Comment by ScottKillen** [comment]
Thanks

**Comment by KarlCastle** [comment]
ITAD have fixed the mismatch and resolved the issue on their tracker.

http://store.steampowered.com/app/361800/Tree_of_Life/ currently has:
Historical Lowest Price: $11.99 at Steam on 12/22/2017

So this can be safely closed.
