### ISSUE TITLE
[Bug?] No suggestions possible anymore for "How long to beat" 

### ISSUE THREAD

**Issue by Giborius** [jshackles/Enhanced_Steam#1500]
Hi there

I already wrote in the steam group and only later realised, that there is this github-forum to report possible bugs and problems. So I post my message here again:

One of the major benefits of "Enhanced Steam" for me is the possibility to directly see the data from "How long to beat". Thats why I, whenever there is no data available*, always click on "click here to help"* to add a link to the game. Lately now this doesn't work properly anymore.

When I click the link it opens "http://www.enhancedsteam.com/gamedata/hltb_link_suggest.php" as it should. But now when I see the correct game listed there, nothing happens. It's just like clicking anywhere else as if it wasn't a link. The only link that still works fine is the "Game not listed" button.

I use the latest Firefox 57.0.1 and I fear it might have something to do with the new quantum engine. My first guesses were that Noscript or uBlock Origin are responsible, but I turned off both addons and it still didn't work. (I also tried it with every addon deactivated save for ES.)

One example where I just had this problem was here: http://store.steampowered.com/app/600660/Kimmy/
(This is just one example of a game, that has no link to HLTB yet, but the problem exists with every game, that has no link yet.)

I hope there is a simple solution to fix this. Thanks a lot already for all your hard work. ES is so great, I often miss the features when I use the Steam client. I think thats a good sign for you. ;)

* Note: My Steam and ES are German, so the correct English phrases that ES uses may be a little bit different

**Comment by jshackles** [comment]
Thanks for the heads up, this issue should now be resolved server-side.  You may need to empty your browser's cache or wait for it to expire to see the changes.

**Comment by Gimlao** [comment]
This bug occurs again now. =/
