### ISSUE TITLE
Don't put "Warning" next to the DRM mention, make it less "bad" looking

### ISSUE THREAD

**Issue by WilliamFeely** [jshackles/Enhanced_Steam#1553]
When you put "Warning" next to the DRM disclosure on a store page and making it red, are you suggesting that people should boycott the titles in question or that they are harmful?

**Comment by KarlCastle** [comment]
Steamworks incorporates it's own DRM solution. Additional DRM adds more failure modes that might prevent you from playing a game that you've purchased on Steam, like [Bioshock under Windows 10](https://www.rockpapershotgun.com/2015/08/17/windows-10-safedisc-securom-drm/) or anything still dependent on GFWL and that informs potential purchasers' decision making.

The banner is based on information already on the page (that may be in fine print or obscured amongst other details). Red is a great attention gathering color as it is underrepresented in the steam store.

I personally won't pay money for anything with Uplay. Too much hassle when I've tried to install it.

**Comment by WilliamFeely** [comment]
It's still a bit excessive.
As for BioShock my Steam copy launched fine, and all my GFWL games run fine too.
That article you linked to misidentified SecuROM which is a completely different product than Safedisc, which was never used in any Steam game.

A red banner is a bit excessive, and calls into question the legitimacy of this entire project.  Are you saying a PR that makes the color less scary would be rejected, or changes "Warning" to "Notice"?

Also, your first sentence by the way has a grammatical error, it is "its" you should use.

**Comment by jshackles** [comment]
This warning message (yes, warning) and red color has actually prompted several developers to tell me personally that it dissuaded them from putting 3rd party DRM in their games.  They were worried about Enhanced Steam's install base all seeing this message and the impact that might have on sales.  Fortunately, Steam has gotten better about warning users themselves - when this feature was implemented, there was no indication of 3rd party DRM on the store page.  I'd like to think that it's inclusion is a direct result of this feature and the number of users who thought it was a good idea.

If you don't want to see the warning messages, they can be disabled in the options by unchecking "Show 3rd party DRM warnings".

**Comment by WilliamFeely** [comment]
I'd like to say while I disagree with your approach I would like to thank you for remaining civil, unlike the conduct I have seen in the anti-DRM community.
