### ISSUE TITLE
Add Custom Amount Error

### ISSUE THREAD

**Issue by veely** [jshackles/Enhanced_Steam#1575]
![steamerror](https://user-images.githubusercontent.com/20467197/38888323-3be536ce-4249-11e8-896c-53b5d764a5e2.JPG)

Whenever I try to add any custom amount whether using Enhanced Steam or the JS console on Chrome, I get the above error. Is this a server-side issue?

P.S. I've tried both PayPal and credit card.

**Comment by jshackles** [comment]
This is actually already fixed in the dev branch with commit d1a11b9.

This fix will be included in the next release.

**Comment by veely** [comment]
The thing is I was using the code from dev branch. I confirmed I am running version 9.9.
