### ISSUE TITLE
Adding custom amount of money is completely broken

### ISSUE THREAD

**Issue by Leopard1907** [jshackles/Enhanced_Steam#1576]
I'm trying it with both Firefox and Chrome , no matter what amount i type in there it proceeds to add 10 TL (Turkish Lira) to my account.

Firefox , Chrome and ES are both on the latest versions.

**Comment by BryanChung** [comment]
Adding of custom amount (for both Gift Wallet and Personal top-up) does not work for dev 9.9 too. Any help/update on that? Posted in Steam Discussion & Reddit but no reply. Urgently need help on this. :)

**Comment by jshackles** [comment]
The latest fix I made to the 9.9 dev branch (in commit d1a11b9) is still working correctly for me in Chrome.  I just used it to add $7.12 to my Steam wallet.

If the fix isn't working for you, can you let me know if you are getting any error messages in the browser console (F12)?

**Comment by BryanChung** [comment]
Sorry I am not so technical at this. but what I got was this:

![2018-04-23_124312](https://user-images.githubusercontent.com/6512798/39107296-ed5a1cf4-46f3-11e8-8f9b-12cfb53bd835.png)

I tried manually changing the data-amount and didn't work too. And yes, I'm sure I'm using 9.9. 

![2018-04-23_124354](https://user-images.githubusercontent.com/6512798/39107310-038f6f42-46f4-11e8-8f49-a966e936b1e1.png)

**Comment by jshackles** [comment]
@BryanChung Thanks for the update, it looks like this has to do with how your country's currency is formatted.  I'll try running the add_custom_money_amount() function through the parse_currency() function prior to assigning the value which should clear that error and allow the function to work correctly.

Curious - did it work for you before Valve made their most recent changes?  It doesn't seem like it should have.

**Comment by BryanChung** [comment]
Thanks for looking into it and fast! 

Erm, I didn't try it until 4 days ago then realised I cannot add custom amount. I was trying to purchase custom amount for a friend, then realised both gift wallet and personal purchase doesn't work.

Will the gift custom amount for friend works too?

**Comment by jshackles** [comment]
Once this function gets fixed up properly, it should work for both pages.

**Comment by BryanChung** [comment]
Great! You're working on a fix now? It will be in dev or stable channel?

**Comment by jshackles** [comment]
The fix will probably be ready some time in the next 24 hours, and it will roll out to the dev branch first.  Stay tuned.

**Comment by BryanChung** [comment]
Ok! Will be a new version number I supposed?

**Comment by BryanChung** [comment]
Doesn't seem to work. :(

I got that error when I click purchase after custom input of SGD $4.00. Trying to buy that wallet amount for a friend.

![2018-04-24_001503](https://user-images.githubusercontent.com/6512798/39139473-9bf3a2f2-4754-11e8-8b30-6a05949100a7.png)

Here's the previous screen.

![2018-04-24_001631](https://user-images.githubusercontent.com/6512798/39139528-bfe74a06-4754-11e8-8831-c6e490b9ffd0.png)

**Comment by jshackles** [comment]
It appears that S$6 is the minimum purchase amount in your region, so any amount less than that would result in the transaction error you're seeing.

**Comment by Leopard1907** [comment]
@jshackles 9.9 dev branch fixed to issue for me. Thanks.
