### ISSUE TITLE
Continuous scrolling reviews

### ISSUE THREAD

**Issue by mdekleine** [jshackles/Enhanced_Steam#282]
When viewing the reviews on a store page, Steam only shows the first 5 reviews. You have to click a button to load more. Perhaps this can be made that it loads automatically when hitting the bottom of the page?

**Comment by seeeeew** [comment]
Currently 10 reviews are shown by default and it's just one click more to get to an auto-loading page, so I think this should be closed.

**Comment by JoiNNN** [comment]
Agree 👍
