### ISSUE TITLE
Add the "Add to IsThereAnyDeal Waitlist" button

### ISSUE THREAD

**Issue by enchained** [jshackles/Enhanced_Steam#291]
I have a really big wishlist on Steam, cause I add every interesting new game there. It would be useful, if instead of that I could add a game from its page to isthereanydeal.com waitlist, or even see if that game is already in my ITAD waitlist. Automatical adding with preset parameters like price/percent/shops would be amazing too. I guess the add button should be near ITADs' lowest price/historical minimum bar.

**Comment by seeeeew** [comment]
ITAD can automatically import your wishlist based on predefined parameters, so I think this should be closed.

**Comment by enchained** [comment]
I already used that ITAD import for years. But the whole point of this suggested feature was "not having the game on the Steam wishlist at all", cause Steam will notify no matter how small is the discount. There's a lot more games that I'd buy on historical lowest discount than I'd buy on any discount, so it doesn't make sense keeping them all on Steam wishlist.
