### ISSUE TITLE
Filter/highlight by OS compatibility

### ISSUE THREAD

**Issue by MegaMissingno** [jshackles/Enhanced_Steam#317]
I'm on Linux, and I've always been annoyed by how the front page doesn't tell me right away what has a port, I have to mouse over each game one by one to check them all. Would be really convenient if you could add an option to automatically highlight games by platform.

**Comment by JoiNNN** [comment]
This is old and I don't think it can be achieved anymore unless the 'appdetails' data pulling is implemented in ES API, with client side caching.
