### ISSUE TITLE
Removing wishlisted game from store-page not working

### ISSUE THREAD

**Issue by hurda** [jshackles/Enhanced_Steam#418]
Firefox 24.3ESR, 27, 28 beta
ES 5.7

Chrome 33
ES 5.9

Trying to remove a wishlisted game from the store page via the "Remove"-link does not work when the login is remembered and the browser has been restarted after entering the login data.

Clicking the "remove"-link would just seemingly refresh the page without doing anything.

Clicking the "remove"-link right after logging in is working fine.

**Comment by JoiNNN** [comment]
This is very old, changes and fixes have been made on how items are removed since then. Can be closed.
