### ISSUE TITLE
Highlight for discounted game

### ISSUE THREAD

**Issue by NekoiNemo** [jshackles/Enhanced_Steam#497]
Highlight the game in wishlist if discount on it exceeds certain (selected in settings of ES).
It would greatly improve the usability of this list.

**Comment by JoiNNN** [comment]
There are several ways now to sort the wishlist by discounts. If this gets requested again we'll look into it.

**Comment by seeeeew** [comment]
ITAD can do this. It can even alert you via E-Mail if the discount is above a certain limit (or the discounted price gets below a certain limit). I din't think this needs to be added to ES.
