### ISSUE TITLE
Make the amount of perfect games in the achievement showcase clickable

### ISSUE THREAD

**Issue by Barokai** [jshackles/Enhanced_Steam#558]
Make the amount of perfect games in the achievement showcase on the profile clickable:

Display the perfect games (with achievements) after a click on the amount or on the subtext "perfect games"

screenshot of the mentioned part of the showcase:
![2014-07-08 09_57_46-steam community __ barokai](https://cloud.githubusercontent.com/assets/2293949/3506775/9bf443a2-0675-11e4-9d08-935bdd7d6b18.png)

**Comment by JoiNNN** [comment]
There is no such data available we can pull to achieve this. We'd need to search every achievement page which is a no go.

_Can be closed._

**Comment by Trinsec** [comment]
If you want to be able to track _achievements_ and _completed games,_ you'd probably better check https://completionist.me/ instead.
