### ISSUE TITLE
0 on cards drops and games with drops remaining

### ISSUE THREAD

**Issue by pepo0939** [jshackles/Enhanced_Steam#564]
Hi. On the Badges page the text that should say haw many card drops remains and how many games with card drops are remaining are showing 0, wild I have a lot of cards drops remaining and games. 
![0 card drops](https://cloud.githubusercontent.com/assets/8195067/3619213/59d635e6-0df2-11e4-9861-a8df53dd1250.jpg)
Any way great job and really useful tool

**Comment by JoiNNN** [comment]
This was fixed some time ago. Can be closed.
