### ISSUE TITLE
Hotkeys Greenlight

### ISSUE THREAD

**Issue by ZeoNish** [jshackles/Enhanced_Steam#594]
A very useful feature for users who often vote on steam Greenlight.
![qip shot - screen 137](https://cloud.githubusercontent.com/assets/8596319/4098058/896fe7d2-2ffa-11e4-835d-32a8db999edd.png)

**Comment by JoiNNN** [comment]
Greenlight is dead. This can be closed.

**Comment by seeeeew** [comment]
I agree. I implemented most of the greenlight stuff and I'll remove it once Greenlight is gone for good.
