### ISSUE TITLE
Integrate browser extension and standalone

### ISSUE THREAD

**Issue by IIsi50MHz** [jshackles/Enhanced_Steam#610]
Currently, the browser extensions tend to support more features than the standalone version. Only the standalone version works in the Steam client and the in-game browser provided by Steam overlay. Running both provides the most features, but causes some elements to be duplicated (and probably duplicates API requests).

Perhaps add something to the browser extension that detects a change written by the standalone version and causes the browser extension to only apply the features which are not yet in standalone?

**Comment by JoiNNN** [comment]
Standalone version is no longer supported. Can be closed.
