### ISSUE TITLE
Show both PC and Mac games in the "Top Sellers" list on the homepage

### ISSUE THREAD

**Issue by garyking** [jshackles/Enhanced_Steam#620]
I have a PC for gaming and a Mac for working. I browse the Steam website on a Mac. When I visit the new Steam homepage on a Mac, it only shows Mac games for the "Top Sellers" list on the bottom of the homepage. I have to click on "See more: Top Sellers" then click on the "X" to remove the Mac label to see ALL top sellers.

I'm wondering if Enhanced Steam can swap out the Top Sellers list for a list of ALL PC and Mac top sellers? I don't know if they've got an API for that (would just require Steam search), or you'd have to scrape the search results yourself, though.

I already contacted Steam about this but I don't have high hopes at all, due to their legendarily horrifically bad support, etc.

**Comment by JoiNNN** [comment]
Steam now has the option to show games  by platform under _**Preferences > PLATFORM PREFERENCES**_. This can be closed.
