### ISSUE TITLE
Improving the PCGamingWiki integration

### ISSUE THREAD

**Issue by connorshea** [jshackles/Enhanced_Steam#635]
Hey guys. I'm a moderator over at the PCGW, and I'm in charge of the iconography, CSS, and general graphics work.

Right now the blue PCGW icon next to "View PCGamingWiki Article" doesn't look all that great with the latest Steam design, and I was wondering if you guys wanted me to submit a pull request with an updated white icon to fit with the theme? And if so, would you like it as an SVG, PNG, or some other format, as well as the preferred resolution?

[See the Half-Life 2 page for an example of the PCGW button](http://store.steampowered.com/app/220/)

Thanks, Connor

**Comment by JoiNNN** [comment]
I think this can be closed.
