### ISSUE TITLE
Owning a game in the inventory do not change title color anymore.

### ISSUE THREAD

**Issue by enchained** [jshackles/Enhanced_Steam#643]
When I own a game in library, title of this game is green on this game page (though unnecessary, cause there is other signs that this game is owned).

When I own a game in inventory (as a gift), title of this game USED to be orange on the game page, but no more.  Now it is not changing from standard white. And there is no way to define if I own this game as a gift or not from game page now.

Other store pages seem to be unaffected, and highlight owned gift items correctly (except of this case: https://github.com/jshackles/Enhanced_Steam/issues/639 )

**Comment by JoiNNN** [comment]
There have been made some changes on how items are highlighted since this was posted, chances are it's fixed.
