### ISSUE TITLE
CSS es_highlight class applied to wishlist page menu

### ISSUE THREAD

**Issue by enchained** [jshackles/Enhanced_Steam#644]
Above the wishlist there is the 5-section menu with links to recent games, all games, followed games, wishlist and reviews. All anchor tags of this menu are contained inside one div. For me this div has following CSS classes: "sectionTabs item es_highlight_inv_guestpass". Which leads to 941x3px bar (in black to orange gradient) between my nickname and these menu buttons.

**Comment by JoiNNN** [comment]
Pretty sure this bug is long gone. Can be closed.
