### ISSUE TITLE
Badges displays wrong amount of pages

### ISSUE THREAD

**Issue by NekoiNemo** [jshackles/Enhanced_Steam#651]
Dunno how to phrase it correctly.
http://puu.sh/cFYRb/d3b38db956.jpg
If you select "Badges With Card Drops Remaining" while having more than 250 badges/WIP badges page selection is still being displayed even though it's useless in this case and leads to other pages of "All badges".

**Comment by JoiNNN** [comment]
This can't be reliably fixed, since we don't know what's on other pages. Some of the sorting/visibility features available on badge pages work only on currently visible page.
