### ISSUE TITLE
Possible issue with Amazon price checks

### ISSUE THREAD

**Issue by joetcherian** [jshackles/Enhanced_Steam#654]
Some steam games show up as 0$ (Amazon external link), but on actually navigating to the page there is no discount and the game is basically selling at normal prices.
I guess the price query on Amazon for the game is returning as 0 causing the Amazon link to pop up.

Is anyone else seeing this on their steam wishlist page too?

**Comment by JoiNNN** [comment]
Probably an ITAD issue at the time. Can be closed.
