### ISSUE TITLE
Discrepancy between market prices and badge page prices

### ISSUE THREAD

**Issue by RawPLowPLow** [jshackles/Enhanced_Steam#660]
Even after refreshing the page and clearing cookies the difference is still here ( hope it helps since I now have to wait 7 days before using the market on my web browser ಠ_ಠ ).
![me](https://cloud.githubusercontent.com/assets/9860153/5307377/d61a18a6-7c0c-11e4-86f2-a2fe27c3cd6d.jpg)

**Comment by JoiNNN** [comment]
This must've been an ES API issue at the time, where some data wasn't updated often enough. Can be closed.
