### ISSUE TITLE
[bug] Problem with GamesRepublic prices

### ISSUE THREAD

**Issue by Slowacki** [jshackles/Enhanced_Steam#665]
As for today, several games on my wishlist list a 0.00€ price on GamesRepublic as I hover my mouse over them. As much as I would like that to be true, those games are at their regular prices.

Games that were 0€:
- This war of mine,
- World of goo.
  As for today, several games on my wishlist list a 0.00€ price on GamesRepublic as I hover my mouse over them. As much as I would like that to be true, they games are at their regular prices.

Games that were 0€:
- This war of mine,
- World of goo.

**Comment by JoiNNN** [comment]
Pretty sure this was a ITAD issue at the time. Can be closed.

**Comment by seeeeew** [comment]
I agree. I don't think ES ever contained any code specific to GamesRepublic.
