### ISSUE TITLE
[Bug] Early Access Titles in Showcase

### ISSUE THREAD

**Issue by Yikal** [jshackles/Enhanced_Steam#666]
I just tried to edit a early access title in my game collector showcase, but was instead redirected to the community site of the game.
After deactivating Enhanced Steam it worked.

**Comment by allicat** [comment]
Also having this problem. I've found that if you go into ES's options and turn off the Early Access banners, it allows you to change them as normal, and still keep the extension running.

Google Chrome for me, it's been this way for a few versions of the browser, but only just tried that option today to see if that was the culprit/clue.

**Comment by JoiNNN** [comment]
Does this still happen? Care to detail how to replicate the issue?

**Comment by Yikal** [comment]
It's not as bad anymore as it was, but sure, I'll give an instruction:

1. Edit your Steam Profile
2. Choose the Game Collector badge
3. Choose at least one early access game to display
4. While still editing the profile, hover over the early access title, the edit icon is now display
5. If you don't exactly click on the edit icon you're redirected to the titles community page

When you do the steps with non-early acces titles, the edit mode is entered even if you don't exactly hit the edit icon

**Comment by JoiNNN** [comment]
Got it, thanks for taking your time to explain. Will be fixed in the next release 👍
