### ISSUE TITLE
Feature: Option to hide or show Steam's own library\wishlist indication

### ISSUE THREAD

**Issue by mdekleine** [jshackles/Enhanced_Steam#670]
Like the title says. The indication by Steam is now replaced by the color, but it is not always correct and up-to-date. Ideally it would be possible to have displayed both indications by Steam and Enhanced Steam. Optionally of course for those who like to choose.

**Comment by JoiNNN** [comment]
The 'dynamicstore' data is now more often updated, which should more accurately reflect wishlist changes.
