### ISSUE TITLE
Show when games are in a bundle at the moment

### ISSUE THREAD

**Issue by xur86x** [jshackles/Enhanced_Steam#672]
Right now there is one game in a Humble Bundle, but when I visit the Steam store page it does not show that. Normally buying a bundle is even cheaper than buying on a discount so that should be shown on the page.

**Comment by mikenerone** [comment]
Similar issue right now with [_Deus Ex: Human Revolution - Director's Cut_](http://store.steampowered.com/app/238010/): ES currently displays lowest price as $15.99 from GMG, but it is included in the current [Humble Bundle](https://www.humblebundle.com/) (_Humble Square Enix Bundle 2_) at the $15.00 unlock level including a boatload of other games.

**Comment by jshackles** [comment]
This is an issue with IsThereAnyDeal and their API.  The bundle section for each game is being re-written in the next release which should help clear this up somewhat.
