### ISSUE TITLE
Option to add player to list on VacStatus tracking page.

### ISSUE THREAD

**Issue by Hooch180** [jshackles/Enhanced_Steam#673]
Hello.
Can you add option that enables to to with one click of button to add player to personal "watch" list on this page?

https://vacstat.us/

**Comment by Kezxo** [comment]
This or just add a link to the profiles vacstat.us page, probably easier.
Would be cool if we could add and edit links that shows up in profiles on our own. Maybe because we don't care about TF2 or just want a new site added.

**Comment by JoiNNN** [comment]
That website seems to be dead. Can be closed.
