### ISSUE TITLE
price comparison and game on bundles history not showing

### ISSUE THREAD

**Issue by FallenZector** [jshackles/Enhanced_Steam#677]
![screenshot_60](https://cloud.githubusercontent.com/assets/10359247/5589034/239fb7de-9148-11e4-9085-3e6ceacb2c24.png)

my plugin usually works but from the last one month it doesn't work anymore.
when i hover the mouse to price it doesn't show prices in other regions and no history of games recorded in bundles shown.
i think it's a bug.

and it says error loading enchanced steam data in the upper part section

**Comment by NCPereira** [comment]
My extension shows "Enhanced Steam ready" yet I'm also having this problem. It was working before, and now the price comparison/price history doesn't show up anymore.

**Comment by JoiNNN** [comment]
Can be closed.
