### ISSUE TITLE
[bug] deleting from wishlist isn't working from game page anymore

### ISSUE THREAD

**Issue by enchained** [jshackles/Enhanced_Steam#680]
Recently I noticed that I can not delete any game from wishlist using its store page. It worked before. But now it "looks" like it was deleted (button changed), but after a few seconds and page refreshing - it is still shown as In wishlist.

**Comment by VladimirMangos** [comment]
I confirm problem existance. Also note that it exist some weeks time already., I considering it as reported and not report by self.
