### ISSUE TITLE
NEED HELP;_;

### ISSUE THREAD

**Issue by risky620** [jshackles/Enhanced_Steam#683]
Well my steam account got hacked and everything got stolen. i sent a ticket to support like 2 weeks ago and there is no respond from steam at all..... my items worth like 300$ i really want them back.. 
one of my friend got hacked earlier, and he lost all his stuff as well. And he got his stuff back, so is it possible to get all my stuff back?
one thing that i don't get is why do I have not got any respond from steam? Did they miss me out or what? plz help.

**Comment by dapil** [comment]
Contact [Steam Support](https://support.steampowered.com/), this plugin is not affiliated with Valve.

**Comment by risky620** [comment]
i did like 2 weeks ago 
and there is no respond from steam at all

**Comment by TheSentry** [comment]
I feel sorry for you, but asking for help here is like asking the manufacturers of smartphone covers for help when they mobile phone is stolen.

**Comment by risky620** [comment]
sigh... i don't know what to do.... steam is not giving a !@#$ to me....
