### ISSUE TITLE
"install steam" button replaced

### ISSUE THREAD

**Issue by jvlomax** [jshackles/Enhanced_Steam#686]
The Enhanced Steam menu replaces the "install steam" button, this is annoying if you have to install steam on a fresh OS install and have to download the client

**Comment by bkDJ** [comment]
It replaces it with an "Enhanced Steam" dropdown. Use it to open Enhanced Steam options. In the "store" section, "hide" heading, untick "Hide 'Install Steam' button". Then, refresh/open any steam page. :)

**Comment by TheWhoAreYouPerson** [comment]
It would be helpful if, instead of entirely replacing it, ES could add 'Install Steam' as one of the dropdown menu options.

**Comment by jshackles** [comment]
Actually it doesn't replace the button at all but adds the Enhanced Steam menu to the same part of the header.  Hiding the "Install Steam" button can be toggled in the settings.

Store -> Hide -> Hide "Install Steam" button
