### ISSUE TITLE
Cannot change custom background

### ISSUE THREAD

**Issue by Millhi** [jshackles/Enhanced_Steam#687]
I once set one and wanted to change it, but the option simply does not show up. The option is activated.

**Comment by jshackles** [comment]
Make sure you're using the latest version of Enhanced Steam (v7.3) and it should show up on your "Edit profile" page.

http://steamcommunity.com/my/edit

There is also a "remove" button which you might try first, then try setting a new one (if simply setting a new one doesn't work).

**Comment by JoiNNN** [comment]
Can be closed.
