### ISSUE TITLE
Launch Random Game

### ISSUE THREAD

**Issue by RobLoach** [jshackles/Enhanced_Steam#692]
A small button to launch a random Steam game from your library, for the given platform.

**Comment by TheSentry** [comment]
An additional option to only choose a game that has some achievements left would be nice. (Except for The Stanley Parable)

**Comment by Misch-** [comment]
It seems launching a random steam game from your library exists. Maybe you meant specifically for your platform? Not sure what the implementation is.

![](https://i.gyazo.com/a9011c1e3ae756e2b1bc239c5860706f.png)

**Comment by JoiNNN** [comment]
This would also require an ES API implementation for 'appdetails' to pull platform info for owned games.
