### ISSUE TITLE
Feature: label mobile ports

### ISSUE THREAD

**Issue by alidan** [jshackles/Enhanced_Steam#693]
i dont know about other people but i tend to find most mobile ports are not worth my time however, not every game gives itself away that its a mobile port from the get go, and there are a few games i bought (granted really cheap) that i didn't know they were mobile ports till after i bought them only to come out disappointed.

if there was a way to do a warning like there is with 3rd party drm, that would great
if there was a way to do it before you even click the game in search like owned wishlisted games, even better.

also, sorry if this doesn't go here. git hub always confused me

**Comment by JoiNNN** [comment]
There is no data at hand ES can look into if a game is a mobile port. Can be closed.
