### ISSUE TITLE
Price comparison on Wishlist issue.

### ISSUE THREAD

**Issue by iceatcs** [jshackles/Enhanced_Steam#694]
The Price History Information should be display on Wishlist, but it didn't do any more. 
Other pages seem fine, just "Wishlist" page have this problem.

Any idea what the problem? Maybe Valve have change the wishlist source page.

**Comment by jshackles** [comment]
It's still working fine here.  Be sure that you have Options -> Price -> Price History -> Show on Wishlist checked in the settings.

**Comment by iceatcs** [comment]
Already ticked on it. 

I have just solved the problem, by logout then, clear cookie and log in again.
Anyway Thanks for fast reply.
