### ISSUE TITLE
'How Long To Beat' section missing in some games

### ISSUE THREAD

**Issue by dpares** [jshackles/Enhanced_Steam#695]
I've noticed the HLTB section is not showing up for some games that actually have an entry in HLTB. Examples include Garry's Mod, Street Fighter X Tekken y BlazBlue: Calamity Trigger.

When querying the Enhanced Steam API for one of those game's HLTB data, I get an empty response. For example, this happens with [SFxT](http://api.enhancedsteam.com/hltb/?appid=209120), although [there's a valid entry in HLTB](http://howlongtobeat.com/game.php?id=9246). 

I'm assuming ES queries HLTB using the game's name. If that's the case, I don't really see why would some games fail since not all of them have special symbols (and others, like Injustice: Gods Among Us, work).

**Comment by jshackles** [comment]
Actually, Enhanced Steam has a manual database with entries that link the HLTB scores with their associated Steam AppIDs.  This ensures that the information that's displayed is always for the correct game and doesn't rely on text searches.

Of course the downside to this method, as you've discovered, is that not all games that are available on HLTB are available through Enhanced Steam.  As new games are added to Steam and HLTB, there is a process that must take place linking the two pages.  At present, only about 700 games on Steam are linked in this way (or roughly 1 out of 5).  More are being added / updated as time allows.

**Comment by jshackles** [comment]
Due to the nature of how this is set up, it will most likely always be true that there will be games on Steam that are missing information from How Long To Beat.  As such, I'll be closing this issue as the titles mentioned here have all been added to the database now.
