### ISSUE TITLE
Doom & Destiny

### ISSUE THREAD

**Issue by seanmaxwell99** [jshackles/Enhanced_Steam#698]
http://store.steampowered.com/app/318130/

Steam page, EnhancedSteam currently states it is being sold on ShinyLoot. The problem is, ShinyLoot give you a Desura Key upon purchase, not a Steam key.

**Comment by jshackles** [comment]
This is expected behavior.  Any game in the "lowest price" section that has been confirmed to include a Steam key will explicitly say "Activates on Steam" next to the price.
