### ISSUE TITLE
[Bug] Button to decline invalid trades offers missing

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#701]
Works on http://steamcommunity.com/id/username/tradeoffers/ but not on http://steamcommunity.com/id/username/tradeoffers

http://i.imgur.com/KJq8UF8.png
http://i.imgur.com/XDSCmQ1.png

**Comment by jshackles** [comment]
Thanks for the heads up.  This is an easy fix, so it will be available in the next release.
