### ISSUE TITLE
No Longer shows prices!

### ISSUE THREAD

**Issue by chad78** [jshackles/Enhanced_Steam#702]
The best / main feature is now missing for me.  I cannot see any price comparisons at all!

**Comment by chad78** [comment]
![missing](https://cloud.githubusercontent.com/assets/5626058/6819807/f9eeb7bc-d294-11e4-9001-085855f788e0.png)
You can see, I have the extension - it is installed, and the content is fully loaded (the green line has become a circle), but there is no price comparison.  Hovering over and even clicking on the price box does not help.
Google Chrome Version 41.0.2272.104 (64-bit) on Mac OS X 10.10.2 (14C109)

**Comment by chad78** [comment]
You can see, I have the extension - it is installed, and the content is fully loaded (the green line has become a circle), but there is no price comparison. Hovering over and even clicking on the price box does not help.
Google Chrome Version 41.0.2272.104 (64-bit) on Mac OS X 10.10.2 (14C109)

![missing](https://cloud.githubusercontent.com/assets/5626058/6819824/6b0116ca-d295-11e4-98e6-dc60c2739c3d.png)

**Comment by Wynillo** [comment]
Same for me.
Google Chrome 41.0.2272.101 m
Windows  7 Professional
![unbenannt](https://cloud.githubusercontent.com/assets/7262244/6820056/59b14620-d2cb-11e4-86ae-88e8ebba578c.PNG)
It stays like this in Whishlist forever btw.

**Comment by jshackles** [comment]
This should be resolved now, there was an issue with the price history API that has been corrected.

**Comment by chad78** [comment]
Yes, it is working now.  Thanks!
