### ISSUE TITLE
Badges Steam Page does not display any of Enchanced Steam's features

### ISSUE THREAD

**Issue by DARKKi** [jshackles/Enhanced_Steam#708]
Badges Steam Page (http://steamcommunity.com//id/YOURID/badges/) does not display any of Enchanced Steam's features but does display Enchanced Steam's option "tab" so it is enabled. I have tried to reinstall and clear cache but no use.

![enchanced](https://cloud.githubusercontent.com/assets/5562502/6939786/9ca140b8-d878-11e4-95fb-ac889519fa56.jpg)

**Comment by jshackles** [comment]
In this instance, there are two slashes "//id" in the URL that are causing issues with Enhanced Steam detecting which page you're on.  Some of Valve's servers are (randomly) inserting links formatted this way for unknown reasons.  I'll be providing a fix in the next update but in the meantime you can simply delete one of the two slashes and it should correct the issue.

**Comment by DARKKi** [comment]
Thanks you for this! And thanks for so fast support! Enchanced Steam is almost essential tool and with so good developement and support i will be sure to donate! Keep up the good work!

This ticket can be closed.
