### ISSUE TITLE
[Bug] ES deletes picture tags

### ISSUE THREAD

**Issue by tkossak** [jshackles/Enhanced_Steam#714]
Chrome Version 42.0.2311.90 m (64-bit)
Enhanced Steam extension v7.4
Os: Windows 7 x64

The picture tags (in wishlist/in library) disappear when i enable ES:

WITHOUT enhanced steam: https://www.diigo.com/item/image/ki7f/2xug
WITH enhanced steam enabled: https://www.diigo.com/item/image/ki7f/tsx4
Source URL: http://store.steampowered.com/sale/roguelike

It happens probably because ES tries to color the games with green (owned) and blue (wishlist) but the color is not visible at all, yet the picture tags are deleted.

**Comment by CorruptComputer** [comment]
This happens to me as well.

**Comment by jshackles** [comment]
This is due to the new sales layout used specifically in this sale, which ends in about 1 hour.  I'll look into fixing this behavior if Valve continues using this same sales layout in the future.

**Comment by JoiNNN** [comment]
Can be closed (?)
