### ISSUE TITLE
[Bug] Early Access image banners no longer appear

### ISSUE THREAD

**Issue by yamalight** [jshackles/Enhanced_Steam#717]
Basically what title says - for some time now I am not able to see Early Access banners anywhere.
See the screenshot below:
![Screenshot from "All new releases"](http://i.imgur.com/AzlDMFb.png)

**Comment by jshackles** [comment]
This bug is fixed in commit 20efe70 and will be part of the next release.

**Comment by yamalight** [comment]
any ETAs on that release?

**Comment by jshackles** [comment]
Most likely some time later this week.

**Comment by yamalight** [comment]
great, thanks
