### ISSUE TITLE
[Feature] "Not interested" buttons for games in lists

### ISSUE THREAD

**Issue by VladimirMangos** [jshackles/Enhanced_Steam#718]
"Not interested" marks help cleanup lists view discount lists for example so useful.
But currently  game marking as  "Not interested" required open game page. Lot time lost in result in attempt mark some addon spam from show in lists.

I suggest add some fast access to "Not interested" button for game in lists if this possible.

**Comment by JoiNNN** [comment]
Valve added this feature. Can be closed.
