### ISSUE TITLE
Not valid payment.

### ISSUE THREAD

**Issue by ArchiStd** [jshackles/Enhanced_Steam#722]
Today i decided to use enhanced steam for the first time. I tried to pay 11.54E, but i didn't receive my moneys on steam. The moneys from PaySafe Card were gone.
![problem](https://cloud.githubusercontent.com/assets/12628284/7838784/0afc4c0a-048f-11e5-9717-ea25890e8f0b.png)

**Comment by jshackles** [comment]
This is an issue you'll need to bring up to Steam Support (https://support.steampowered.com/)
