### ISSUE TITLE
Add custom emoticons from text

### ISSUE THREAD

**Issue by jshackles** [jshackles/Enhanced_Steam#74]
Replace regular text with available emoticons. This means anyone browsing with Enhanced Steam will see the emoticon rather than the text.

This will need to work with web chat if possible.

**Comment by seeeeew** [comment]
Steam has emoticons and mixing Steam emoticons with custom ones would be a bad idea in my opinion. I think this should be closed.

**Comment by JoiNNN** [comment]
I think Steam website didn't used to parse the text for icons as it did(does) in Steam's chat window (?) 
If this was the issue at that time then is long time fixed.

**Comment by seeeeew** [comment]
I think Steam emoticons were introduced in 2014, but I'm not sure.
