### ISSUE TITLE
"Sort by" is not working

### ISSUE THREAD

**Issue by doug098765** [jshackles/Enhanced_Steam#741]
Attempting to sort a list of games in the store causes the list to go gray like it is working but the list never updates to the chosen sort option and all the items in the list stay gray.  I am using the latest version of chrome and I have been noticing this for a few weeks at least.

**Comment by jshackles** [comment]
![Do you mean this list?](http://i.imgur.com/BcNolc7.png)

**Comment by doug098765** [comment]
Yes I do.

**Comment by jshackles** [comment]
Does the "sort by" feature work when Enhanced Steam is disabled?  This is just a regular part of Steam and Enhanced Steam doesn't interact with it in any way.

**Comment by doug098765** [comment]
No it does not work when disabled.  I should have checked that first, sorry.

**Comment by jshackles** [comment]
No problem (this sort of mix-up happens all the time ;)  )  You may want to submit a support ticket to [Steam Support](https://support.steampowered.com/)
