### ISSUE TITLE
[Bug] No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by Sharpie357** [jshackles/Enhanced_Steam#745]
While visiting any game page. For example (GTA IV): http://store.steampowered.com/app/12210/
Progress hangs at 0%, then shows red bar/square under profile picture. 
DRM warning appears, but no price info appears. 

Win 7 64bit. Latest version of Chrome.

Error Messages:

XMLHttpRequest cannot load https://store.steampowered.com/dynamicstore/userdata/?id=50470222. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://store.steampowered.com' is therefore not allowed access.
chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:4  Enhanced Steam v7.5.2 by jshackles  http://www.enhancedsteam.com 
http://api.enhancedsteam.com/early_access/ Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/early_access/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/exfgls/ Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/exfgls/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/metacritic/?mcurl=http://www.metacritic.com/game/pc/grand-theft-auto-iv Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/metacritic/?mcurl=http://www.metacritic.com/game/pc/grand-theft-auto-iv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/pricev3/?subs=1220,36044,28988,6516,&stores=st…dgets,newegg,gamesrepublic,coinplay,funstock&cc=US&appid=12210&coupon=true Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/pricev3/?subs=1220,36044,28988,6516,&stores=st…dgets,newegg,gamesrepublic,coinplay,funstock&cc=US&appid=12210&coupon=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/hltb/?appid=12210 Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/hltb/?appid=12210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/wsgf/?appid=12210 Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/wsgf/?appid=12210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/charts/?appid=12210 Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/charts/?appid=12210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/steamspy/?appid=12210 Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/steamspy/?appid=12210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.
http://api.enhancedsteam.com/playfire/?appid=12210 Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
store.steampowered.com/:1 XMLHttpRequest cannot load http://api.enhancedsteam.com/playfire/?appid=12210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg' is therefore not allowed access. The response had HTTP status code 522.

**Comment by jshackles** [comment]
This error (522 Origin Timeout) should be resolved now and were a result of server outages.
