### ISSUE TITLE
Standalone app interferes with Windows Modern Apps connectivity

### ISSUE THREAD

**Issue by DouglasBrunet** [jshackles/Enhanced_Steam#756]
Using the Enhanced Steam Standalone app makes it so Windows Store (Metro / Modern) apps can't connect to the internet. For some reason, because of how the proxy for Enhanced Steam is configured, Metro apps can't connect at all until the proxy is manually disabled, at which point Enhanced Steam no longer works.

**Comment by dpeukert** [comment]
The Standalone project is discontinued: http://www.enhancedsteam.com/blog/enhanced-steam-standalone-project-discontinued/
