### ISSUE TITLE
Early access corner banners missing.

### ISSUE THREAD

**Issue by Souldrifter** [jshackles/Enhanced_Steam#759]
This just happened this week, I think. Used to work fine before. Before anyone asks, I'm not running Privacy Badger or Ghostery. :)

**Comment by Souldrifter** [comment]
On the wishlist, sorry. I file bugs for a living, so you'd think I could do this in a helpful way, but I'm off the clock and get lazy.

**Comment by Zerathos** [comment]
Do you have 200 items in your wishlist? If so, see #752.

**Comment by Souldrifter** [comment]
Nope. 99.

**Comment by JoiNNN** [comment]
This should be fixed.
