### ISSUE TITLE
Windows Edition is Removed [link inside]

### ISSUE THREAD

**Issue by ardaozkal** [jshackles/Enhanced_Steam#765]
I believe that there has been a problem and it got removed. So I uploaded it for you guys.

Also if it was intended please remove this issue.

Sorry for misusing the issue part.

**Comment by Zerathos** [comment]
By Windows Edition, do you mean Enhanced Steam Standalone? That was discontinued, so any  removal is likely intentional.

**Comment by jshackles** [comment]
Yes, the Standalone application was intentionally removed as it was causing a huge number of support requests.  You can read more about it here: http://www.enhancedsteam.com/blog/enhanced-steam-standalone-project-discontinued/
