### ISSUE TITLE
[Bug] Display problems on wishlist page

### ISSUE THREAD

**Issue by starise** [jshackles/Enhanced_Steam#801]
As you can see below, "Links" pop-up doesn't appear and number of items is not shown..

![Wishlist display problems](http://s10.postimg.org/ec5b1snw9/wishlist.jpg)

**Comment by jshackles** [comment]
Actually, the issue with the links is on Valve's end - this bug exists even if Enhanced Steam is completely disabled.  :(

I'll get the number thing fixed up though, I think it was due to a change we made in how the translation of that string happened.

**Comment by starise** [comment]
Yup, thx. I just realized that the pop-up doesn't appear even with ES disabled.

**Comment by seeeeew** [comment]
Sorry, the translation thing was my fault. Missed that one in dd6f6a69. 😔
