### ISSUE TITLE
[Suggested feature] Allow to mark not relevant for software 

### ISSUE THREAD

**Issue by Black4Blade** [jshackles/Enhanced_Steam#822]
Hello just wanted to suggest as i noticed that Performance Survey dose not allow you to mark something as not relevant, for example software dose not have frame rate and the like, or may not run on Full Screen at all (also maybe a desktop game if we ever going to have one)
So i like to suggest to be able to mark some things as not relevant for the software/game that you run..

**Comment by jshackles** [comment]
Not answering a question (leaving the defaults as "Not Sure") is the same as marking something as not relevant.
