### ISSUE TITLE
[Bug] Greenlight cache isn't updated on vote change

### ISSUE THREAD

**Issue by seeeeew** [jshackles/Enhanced_Steam#839]
When an existing vote on a Greenlight item is changed within 1 hour after caching the data, the old vote is previewed on browsing pages. Changing the vote should update or invalidate the cache.

**Comment by JoiNNN** [comment]
Greenlight is dead. This can be closed.

**Comment by seeeeew** [comment]
I agree. I implemented most of the greenlight stuff and I'll remove it once Greenlight is gone for good.

**Comment by seeeeew** [comment]
I agree. I implemented most of the greenlight stuff and I'll remove it once Greenlight is gone for good.
