### ISSUE TITLE
More Like This-section has an vertical scrollbar when it contains owned products

### ISSUE THREAD

**Issue by petetnt** [jshackles/Enhanced_Steam#848]
![image](https://cloud.githubusercontent.com/assets/7641760/10302342/171bd75c-6c14-11e5-8c56-f06e1aa497ea.png)

The prices are overflowing too:

![image](https://cloud.githubusercontent.com/assets/7641760/10302352/2fc8e36c-6c14-11e5-919c-4e9b7c9af041.png)

**Comment by seeeeew** [comment]
As a workaround you could deactivate tagging owned games, since they're already highlighted.
