### ISSUE TITLE
Recommend to remove Desura store prices / links

### ISSUE THREAD

**Issue by circuit1982** [jshackles/Enhanced_Steam#853]
Desura's parent filed for bankruptcy back in June 2015. (Source: http://www.polygon.com/2015/6/5/8736595/desuras-parent-company-files-for-bankruptcy-ceo-remains-silent )

This has affected Desura, and they are now unable to deliver newly purchased games to their customers.  

I've recently tried to purchase a game from Desura, and they have been unable to provide: a confirmation email to complete my registration, a receipt for the purchase / payment of the game, and the email with the steam key / link for the game.

I was lead to the Desura site through Enhanced Steam, and I think that Desura price listings should be removed from Enhanced Steam before more people get scammed and lose money.

I've also posted this issue to the ITAD GIT page, since Enhanced Steam appears to use ITAD to get price listings.

**Comment by seeeeew** [comment]
You can manually disable Desura in the *Price* section of the Enhanced Steam options after you deactivate *Compare all stores*.

**Comment by circuit1982** [comment]
seeeeew, thanks for the information on manually disabling store listings on Enhanced Steam. I still feel that Desura should not be included in Enhanced Steam, or at least its listings should not be enabled by default. The company has **shut down**, but left their web site online and they are still accepting payments. They are currently taking money from customers and not delivering their products (this is theft).

**Comment by seeeeew** [comment]
I agree that Desura probably shouldn't be enabled by default any more, but it should still be at least an option untill it's gone for good. While it's a bit unlikely it might still be bought and saved.

**Comment by jshackles** [comment]
After reviewing the site and it's situation, I agree that the store needs to be removed.  If something happens to the store in the future and it gets purchased by a more stable company and starts delivering products again, it can be re-added.
