### ISSUE TITLE
CLP (Chilean Pesos) doesn't display correctly

### ISSUE THREAD

**Issue by DarkGhostHunter** [jshackles/Enhanced_Steam#872]
CLP support has been added to Steam and in the price comparison tool displays weird differences between the base currency (CLP) and the compared countries. Example:

![this](https://cloud.githubusercontent.com/assets/5141911/11321522/bbc4e90e-90a1-11e5-8c4a-d77d9ed26448.PNG)

It should take the base currency of the store (in this case, CLP), take the pricing of other countries being compared, show the price difference, and then show the equivalent in the base currency. And "P" should change to CLP.

**Comment by caraelfo** [comment]
if exchange rate is needed $1 USD = $700 CLP

**Comment by Ragna01** [comment]
+1
