### ISSUE TITLE
Videos don't play with Enhanced Steam.

### ISSUE THREAD

**Issue by vagarenko** [jshackles/Enhanced_Steam#873]
Non of the videos that use steam player work when Enhanced Steam is on.
The time indicator says: 0:00 / NaN:NaN

Embeded Youtube videos work fine.
![enhanced steam bug](https://cloud.githubusercontent.com/assets/1395677/11324093/812a1a10-9148-11e5-8322-82393c0ad86c.png)

**Comment by seeeeew** [comment]
I can't reproduce this. Do the videos work when you deactivate Enhanced Steam? Have you tried clearing the ES cache and the browser cache? Do you see error messages in the Javascript console (Ctrl+Shift+J)?

**Comment by vagarenko** [comment]
I'm terrebly sorry.
I've found that it is not Enhanced Steam, but my other extention(Audio EQ) was blocking the videos. 
It did only happen on Steam and didn't happen in incognito mode, so I thought it is Enhanced Steam.
Sorry for inconvenience.
