### ISSUE TITLE
[Suggestion] Trade offer

### ISSUE THREAD

**Issue by TuTAH1** [jshackles/Enhanced_Steam#875]
I want to button "Отправить предложение обмена" ("make a tradeoffer") It is were make link "https://steamcommunity.com/tradeoffer/new/?partner=AccountID". I'm and anyone, I'm sure, very nedded that. Or at least AccountID were in profile like Permalink.

**Comment by thomas-ashcraft** [comment]
Steam already has this function.

1) Click "More" ("Еще...") on target's profile page
2) Click "Offer a Trade..." ("Предложить обмен...")

![untitled-1 gh1](https://cloud.githubusercontent.com/assets/6583664/11387645/afff2604-933d-11e5-87de-cd9c16a33df3.png)

**Comment by TuTAH1** [comment]
But I can do it only for friends

**Comment by jshackles** [comment]
That is a limitation of Steam and there isn't a way around that without knowing the other person's Trade Offer URL.  This isn't a problem that Enhanced Steam will be able to solve.
