### ISSUE TITLE
[Bug] warning in trade offer says "you will recieve nothing from this trade" when the receiver actually receives nothing 

### ISSUE THREAD

**Issue by miklast** [jshackles/Enhanced_Steam#887]
http://prntscr.com/9avc6c

i guess the parameters are backwards?

Basically if you were to make a trade with someone offering nothing for an item (in above screenshotit is cases) you will get a warning saying that you will get nothing from this trade. In reality i am getting everything in the trade (everything meaning everything in the trade) and thus the warning is somewhat misleading and slightly confusing.

**Comment by jshackles** [comment]
I'm not sure where the text in red from your screenshot is coming from, but it's not Enhanced Steam.

**Comment by miklast** [comment]
then its from Steam Inventory Helper then. sorry to waste your time.
