### ISSUE TITLE
Новая функция

### ISSUE THREAD

**Issue by DeadSnow** [jshackles/Enhanced_Steam#888]
Добавьте функцию подсвечивания игр которые отмеченные "Не интересно".

**Comment by seeeeew** [comment]
Could you maybe translate this issue to english?

**Comment by thomas-ashcraft** [comment]
Translation:
> [Suggestion] Please add feature to highlight games, marked as "Not Interested"

Answer is: was already suggested in https://github.com/jshackles/Enhanced_Steam/issues/747 and in https://github.com/jshackles/Enhanced_Steam/issues/619
also guy here https://github.com/jshackles/Enhanced_Steam/issues/847 meant to suggest the same

**Comment by JoiNNN** [comment]
Added. Can be closed.
