### ISSUE TITLE
[Feature Request] Completely hide Steam Curators from Main Store Page

### ISSUE THREAD

**Issue by bFunkh** [jshackles/Enhanced_Steam#956]
I'd like to know if it is at all possible to hide Steam Curators from the main Steam Store Page. At the moment, I've tried by picking some of the curators to only show their recommendations, but neither in Enh. Steam or in the Steam client do I get my chosen Curators to show up any-more. This behaviour has changed from before when it was only necessary to have 1 curator and you'd see all their recommends even if you had all those games. Now it keeps pushing the "Recommended Curators to Follow" on me.

Thanks for all the work you've put in so far.
Cheers

**Comment by JoiNNN** [comment]
You mean like this?
![currr](https://cloud.githubusercontent.com/assets/3322834/13545333/5e14aa22-e288-11e5-87ca-9f6a12a41f61.png)

**Comment by bFunkh** [comment]
Bollocks. I am completely blind. I missed that customize menu there and ofc only checked in the "official" options menu. Don't I look like an utter bumbling retard now :P. I can facepalm myself to infinity.

Thanks, JoiNNN
