### ISSUE TITLE
Add traderep.org links to profiles.

### ISSUE THREAD

**Issue by Kezxo** [jshackles/Enhanced_Steam#957]
Seems like a useful site, just stumbled across it.

**Comment by Royalgamer06** [comment]
`jQuery('div.profile_item_links').append('<div class="profile_count_link"><a href="//www.traderep.org/profiles/' + g_rgProfileData.steamid + '" target="_blank"><span class="count_link_label">TradeRep</span>&nbsp;<span class="profile_count_link_total"><img src="https://www.traderep.org/favicon.ico" class="profile_link_icon"></span></a></div>');`

**Comment by peppage** [comment]
Traderep is gone so this issue should be closed. 😞
