### ISSUE TITLE
[BUG] Unable to switch on off/change the custom theme/background

### ISSUE THREAD

**Issue by oubeichen** [jshackles/Enhanced_Steam#969]
The api server returns code 500. Is there any issue about the api server?

**Comment by jshackles** [comment]
Everything on our server looks like it's working correctly, it appears that Steam's OpenID system may be temporarily offline.  I'll keep an eye on it and if it doesn't come back up I'll reach out to them to see if anything can be done.

**Comment by jshackles** [comment]
This should be working again now, let me know if you're still having issues.
