### ISSUE TITLE
[Bug] Broken currency detection on HTTPS pages

### ISSUE THREAD

**Issue by seeeeew** [jshackles/Enhanced_Steam#972]
While on HTTPS, ES can neither access the HTTP localStorage nor fetch data via HTTP. This means e. g. that all users see their account totals in USD unless they explicitly set another currency in the options.

**Comment by JoiNNN** [comment]
I've attempted a fix on this also @ #967. My bad for making it hard to see, I'll try and make separate issues then reference them as you did from now on.
