### ISSUE TITLE
[BUG] Wrong total price in Community Market (Неправильная сумма заказов на торговой площадке)

### ISSUE THREAD

**Issue by TuTAH1** [jshackles/Enhanced_Steam#979]
I think, 1 screenshot is enough to see this bug:
[IMG]http://s019.radikal.ru/i626/1603/4c/b8196275f48a.png[/IMG]
"Суммарная цена заказов" – total price (of orders), and you can see, that it is not 2.5 rub, only in page that I screen more than 100 rubels and in summary it's a bit less than 2 000, but theres write "2.5 руб". Please, fix it! It's a very usefull features and it's very uncomfortable when it's wrong

Думаю, одного лишь скрина достаточно, что бы понять проблему

**Comment by VladimirMangos** [comment]
Screenshot link broken. But I can confirm problem. Possible related wrong parsing "," and "." in float prices. In russian regional settings "," used as decimal mark.

**Comment by VladimirMangos** [comment]
Correction: It's not related float format. In fact total price just show price first element of Buy Orders list

**Comment by VladimirMangos** [comment]
Problem not happens for me for long time.

**Comment by TuTAH1** [comment]
Yes, now they fix it

**Comment by fadillzzz** [comment]
@TuTAH1 If it's fixed, please close the issue.
