### ISSUE TITLE
[Suggestion] Hide games you don't own

### ISSUE THREAD

**Issue by Ozencb** [jshackles/Enhanced_Steam#990]
Hi, everyone. I know, the title of this issue sounds ridiculous but my main point is a little more than that. I've been searching for a way to sort my library by user ratings and some say that Steam won't allow 3rd parties to use their rating API. The feature only works on Steam store search. Wouldn't it be possible to sort your library by Steam user ratings if you implement a setting in Enhanced Steam to hide all the games you do not own or only show the games you own in the search page? Thank you very much.

**Comment by seeeeew** [comment]
The [SteamDB calculator](https://steamdb.info/calculator/) can sort your library by user ratings.

**Comment by Ozencb** [comment]
I don't know how I missed that one ;_; Thanks a lot!

**Comment by VanityFox** [comment]
So, Enhanced Steam is discontinued. There is now [Augmented Steam](https://github.com/tfedor/AugmentedSteam/). Perhaps your requested feature/bugfix is already implemented there! If not, you could move your issue there.
